// lib/covers/catalog.ts
//
// GENERATED by scripts/covers-build.ts from public/covers/*.png — do not edit by
// hand. It is the SOURCE OF TRUTH for the cover asset library: every entry's
// file exists and every file is catalogued (scripts/test-covers.ts asserts
// both). The images are white-keyed transparent PNGs; there is no external image
// API anywhere in the cover feature.

export type CoverKind = 'city' | 'person' | 'motif'

export type CoverAsset = {
  slug: string
  kind: CoverKind
  /** File under public/covers/, served at /covers/<file>. */
  file: string
  /** Cities / subjects / clusters / audiences the asset suits. */
  tags: string[]
  /** Natural pixel size after processing. */
  width: number
  height: number
}

export const COVER_ASSETS: CoverAsset[] = [
  { slug: "faisalabad", kind: "city", file: "faisalabad.png", tags: ["faisalabad"], width: 1600, height: 838 },
  { slug: "islamabad", kind: "city", file: "islamabad.png", tags: ["islamabad"], width: 1600, height: 619 },
  { slug: "karachi", kind: "city", file: "karachi.png", tags: ["karachi"], width: 1600, height: 670 },
  { slug: "lahore", kind: "city", file: "lahore.png", tags: ["lahore"], width: 1600, height: 423 },
  { slug: "multan", kind: "city", file: "multan.png", tags: ["multan"], width: 1600, height: 566 },
  { slug: "pakistan-map", kind: "city", file: "pakistan-map.png", tags: ["pakistan"], width: 1436, height: 1222 },
  { slug: "peshawar", kind: "city", file: "peshawar.png", tags: ["peshawar"], width: 1600, height: 310 },
  { slug: "rawalpindi", kind: "city", file: "rawalpindi.png", tags: ["rawalpindi"], width: 1600, height: 650 },
  { slug: "biology", kind: "motif", file: "biology.png", tags: ["biology"], width: 763, height: 800 },
  { slug: "book", kind: "motif", file: "book.png", tags: ["subject-guides","reading"], width: 800, height: 650 },
  { slug: "calendar", kind: "motif", file: "calendar.png", tags: ["schedules","boards-exams"], width: 800, height: 699 },
  { slug: "certificate", kind: "motif", file: "certificate.png", tags: ["boards-exams","results"], width: 800, height: 618 },
  { slug: "chat", kind: "motif", file: "chat.png", tags: ["messaging","safety-trust"], width: 800, height: 555 },
  { slug: "computer", kind: "motif", file: "computer.png", tags: ["computer","computer science"], width: 800, height: 473 },
  { slug: "english", kind: "motif", file: "english.png", tags: ["english","writing"], width: 800, height: 426 },
  { slug: "grad-cap", kind: "motif", file: "grad-cap.png", tags: ["tutor-career","results"], width: 800, height: 505 },
  { slug: "home", kind: "motif", file: "home.png", tags: ["home","home tutoring"], width: 800, height: 742 },
  { slug: "maths", kind: "motif", file: "maths.png", tags: ["maths","mathematics"], width: 766, height: 800 },
  { slug: "online", kind: "motif", file: "online.png", tags: ["online","online tutoring"], width: 800, height: 536 },
  { slug: "phone", kind: "motif", file: "phone.png", tags: ["contact","phone"], width: 449, height: 800 },
  { slug: "physics", kind: "motif", file: "physics.png", tags: ["physics"], width: 786, height: 800 },
  { slug: "pin", kind: "motif", file: "pin.png", tags: ["city-guides","area"], width: 565, height: 800 },
  { slug: "quran", kind: "motif", file: "quran.png", tags: ["quran","holy quran"], width: 800, height: 569 },
  { slug: "school", kind: "motif", file: "school.png", tags: ["schools","admissions"], width: 800, height: 770 },
  { slug: "science", kind: "motif", file: "science.png", tags: ["science","chemistry"], width: 800, height: 745 },
  { slug: "search", kind: "motif", file: "search.png", tags: ["search","city-guides"], width: 800, height: 167 },
  { slug: "shield", kind: "motif", file: "shield.png", tags: ["safety-trust","verification"], width: 651, height: 800 },
  { slug: "star", kind: "motif", file: "star.png", tags: ["rating","reviews"], width: 800, height: 760 },
  { slug: "wallet", kind: "motif", file: "wallet.png", tags: ["cost-hiring","fees"], width: 743, height: 800 },
  { slug: "parent-child", kind: "person", file: "parent-child.png", tags: ["parents"], width: 861, height: 1200 },
  { slug: "student", kind: "person", file: "student.png", tags: ["both","student"], width: 807, height: 1200 },
  { slug: "teacher-female", kind: "person", file: "teacher-female.png", tags: ["tutors"], width: 436, height: 1200 },
  { slug: "teacher-male", kind: "person", file: "teacher-male.png", tags: ["tutors"], width: 400, height: 1200 },
]

export const COVER_BY_SLUG: Map<string, CoverAsset> = new Map(COVER_ASSETS.map((a) => [a.slug, a]))

export function coverAsset(slug: string | null | undefined): CoverAsset | null {
  return slug ? COVER_BY_SLUG.get(slug) ?? null : null
}
