// lib/payments/manual.ts
//
// Bank / JazzCash / Easypaisa transfer, approved by a finance admin.
//
// This is the fallback while AssanPay is being signed, and it stays afterwards
// as the admin-side path for a member whose card fails. It is deliberately
// honest about timing: a manual transfer is NOT instant, and CLAUDE.md forbids
// saying it is. The copy says "usually activated within a few hours".
//
// Account details are never hardcoded (CLAUDE.md rule 7). They come from
// app_settings, which an admin can change without a deploy, falling back to
// env vars so a fresh environment still works.

import { createClient } from '@/lib/supabase/server'
import type {
  CheckoutIntent,
  CheckoutResult,
  ManualInstructions,
  PaymentProvider,
  WebhookEvent,
} from './provider'

const SETTING_KEYS = {
  bankName: 'pay.bank_name',
  accountTitle: 'pay.account_title',
  iban: 'pay.iban',
  jazzcash: 'pay.jazzcash',
  easypaisa: 'pay.easypaisa',
} as const

/**
 * Where members are told to send money.
 * app_settings first, env second, null last -- a channel with no details is
 * not offered rather than shown blank.
 */
export async function manualInstructions(): Promise<ManualInstructions> {
  const supabase = await createClient()
  const { data } = await supabase
    .from('app_settings')
    .select('key, value')
    .in('key', Object.values(SETTING_KEYS))

  const stored = new Map((data ?? []).map((r) => [r.key as string, (r.value as string) || null]))
  const pick = (key: string, env: string | undefined) =>
    (stored.get(key) ?? null) || (env?.trim() || null)

  return {
    bankName: pick(SETTING_KEYS.bankName, process.env.MANUAL_PAY_BANK_NAME),
    accountTitle: pick(SETTING_KEYS.accountTitle, process.env.MANUAL_PAY_ACCOUNT_TITLE),
    iban: pick(SETTING_KEYS.iban, process.env.MANUAL_PAY_IBAN),
    jazzcash: pick(SETTING_KEYS.jazzcash, process.env.MANUAL_PAY_JAZZCASH),
    easypaisa: pick(SETTING_KEYS.easypaisa, process.env.MANUAL_PAY_EASYPAISA),
  }
}

/** Which transfer methods we can actually accept right now. */
export function availableMethods(
  i: ManualInstructions,
): { code: 'bank' | 'jazzcash' | 'easypaisa'; label: string }[] {
  const out: { code: 'bank' | 'jazzcash' | 'easypaisa'; label: string }[] = []
  if (i.iban) out.push({ code: 'bank', label: 'Bank transfer' })
  if (i.jazzcash) out.push({ code: 'jazzcash', label: 'JazzCash' })
  if (i.easypaisa) out.push({ code: 'easypaisa', label: 'Easypaisa' })
  return out
}

export const manual: PaymentProvider = {
  id: 'manual',
  label: 'Bank or mobile wallet transfer',

  // Always available: it needs no integration, only account details, and a
  // page with no details still explains the situation rather than 500ing.
  isConfigured: () => true,

  async createCheckout(intent: CheckoutIntent): Promise<CheckoutResult> {
    // Nothing to call. The reference is generated by the caller and printed on
    // the instructions page; the member quotes it in their transfer.
    return { kind: 'manual', provider: 'manual', reference: intent.reference }
  },

  // A bank transfer has no webhook. Approval is a human decision, taken on
  // /admin/payments and written to the audit log.
  async verifyWebhook(): Promise<WebhookEvent | null> {
    return null
  },
}
