-- 80_taxonomy_2026.sql — replace the whole taxonomy with the owner's
-- corrected dataset (owner, 12 Sep 2026). GENERATED from
-- supabase/seed/taxonomy-2026.csv by scripts/build-taxonomy-2026.ts —
-- do not hand-edit; re-run the generator.
--
-- SUPERSEDES migration 79. The live taxonomy was miscategorised and its
-- subjects were fanned mechanically across levels (Grade 1 and Grade 5
-- carried identical lists). The CSV is authoritative and per-grade:
-- 13 levels · 29 grades · 480 subjects · 1,475 combinations, VERBATIM.
--
-- Every prior taxonomy_level is flagged legacy — still valid on existing
-- job_subjects / tutor_subjects (they render by id and match by master-id
-- intersection), hidden from the pickers, re-picked on next edit. lib/
-- taxonomy.ts builds the tree and every picker from non-legacy rows only.

begin;
set local client_encoding = 'UTF8';

alter table public.taxonomy_levels add column if not exists legacy boolean not null default false;

-- 1. Retire the entire prior taxonomy. Scoped to slugs this migration did
--    NOT mint, so a re-run cannot retire the rows it just created.
update public.taxonomy_levels set legacy = true where slug not like 'x80g-%';

-- 2. Categories: reuse an existing row with the byte-identical name, else
--    insert fresh. The 3 CSV names with no match ("Pre - Primary /
--    Pre - School", "Matriculation / Secondary", "Teaching of Holy Quran")
--    are inserted; the old "Pre-Primary / Pre-School" / "Matriculation" /
--    "Holy Quran" rows keep their (now all-legacy) grades and fall out of
--    the pickers on their own — no category needs a legacy flag.
insert into public.taxonomy_categories (slug, name, sort_order)
select v.slug, v.name, v.sort_order from (values
  ('x80c-pre-primary-pre-school', 'Pre - Primary / Pre - School', 1),
  ('x80c-primary', 'Primary', 2),
  ('x80c-middle-lower-secondary', 'Middle / Lower Secondary', 3),
  ('x80c-matriculation-secondary', 'Matriculation / Secondary', 4),
  ('x80c-igcse', 'IGCSE', 5),
  ('x80c-intermediate', 'Intermediate', 6),
  ('x80c-adp-2-years', 'ADP (2 Years)', 7),
  ('x80c-bs-4-years', 'BS (4 Years)', 8),
  ('x80c-test-preparations', 'Test Preparations', 9),
  ('x80c-ms-mphil', 'MS / MPhil', 10),
  ('x80c-teaching-of-holy-quran', 'Teaching of Holy Quran', 11),
  ('x80c-sports-games', 'Sports & Games', 12),
  ('x80c-ib', 'IB', 13)
) as v(slug, name, sort_order)
where not exists (select 1 from public.taxonomy_categories c where c.name = v.name)
on conflict do nothing;

update public.taxonomy_categories c set sort_order = v.sort_order from (values
  ('Pre - Primary / Pre - School', 1),
  ('Primary', 2),
  ('Middle / Lower Secondary', 3),
  ('Matriculation / Secondary', 4),
  ('IGCSE', 5),
  ('Intermediate', 6),
  ('ADP (2 Years)', 7),
  ('BS (4 Years)', 8),
  ('Test Preparations', 9),
  ('MS / MPhil', 10),
  ('Teaching of Holy Quran', 11),
  ('Sports & Games', 12),
  ('IB', 13)
) as v(name, sort_order) where c.name = v.name;

-- 3. Grades (taxonomy_levels): 29 fresh non-legacy rows, joined to their
--    category by name, ordered within the category as the CSV lists them.
insert into public.taxonomy_levels (slug, category_slug, name, sort_order, legacy)
select v.slug, c.slug, v.grade, v.sort_order, false from (values
  ('x80g-1', 'Pre - Primary / Pre - School', 'Pre Nursery / Play Group / KG I', 1),
  ('x80g-2', 'Pre - Primary / Pre - School', 'Nursery / KG - II', 2),
  ('x80g-3', 'Pre - Primary / Pre - School', 'Prep / KG- III', 3),
  ('x80g-4', 'Primary', 'Grade 1', 1),
  ('x80g-5', 'Primary', 'Grade 2', 2),
  ('x80g-6', 'Primary', 'Grade 3', 3),
  ('x80g-7', 'Primary', 'Grade 4', 4),
  ('x80g-8', 'Primary', 'Grade 5', 5),
  ('x80g-9', 'Middle / Lower Secondary', 'Grade 6', 1),
  ('x80g-10', 'Middle / Lower Secondary', 'Grade 7', 2),
  ('x80g-11', 'Middle / Lower Secondary', 'Grade 8', 3),
  ('x80g-12', 'Matriculation / Secondary', 'Grade 9 - Arts', 1),
  ('x80g-13', 'Matriculation / Secondary', 'Grade 10 - Arts', 2),
  ('x80g-14', 'Matriculation / Secondary', 'Grade 9 - Science', 3),
  ('x80g-15', 'Matriculation / Secondary', 'Grade 10 - Science', 4),
  ('x80g-16', 'IGCSE', 'IGCSE Core', 1),
  ('x80g-17', 'IGCSE', 'O Levels', 2),
  ('x80g-18', 'IGCSE', 'AS & A Levels', 3),
  ('x80g-19', 'Intermediate', 'FA ( Part I & Part II)', 1),
  ('x80g-20', 'Intermediate', 'FSC Part I & Part II', 2),
  ('x80g-21', 'ADP (2 Years)', 'All Programs', 1),
  ('x80g-22', 'BS (4 Years)', 'Semester 1 - 8', 1),
  ('x80g-23', 'Test Preparations', 'All Tests', 1),
  ('x80g-24', 'MS / MPhil', 'Semester 1 - 6', 1),
  ('x80g-25', 'Teaching of Holy Quran', 'Teaching of Holy Quran', 1),
  ('x80g-26', 'Sports & Games', 'Sports & Games', 1),
  ('x80g-27', 'IB', 'PYP', 1),
  ('x80g-28', 'IB', 'MYP', 2),
  ('x80g-29', 'IB', 'Diploma', 3)
) as v(slug, category_name, grade, sort_order)
join public.taxonomy_categories c on c.name = v.category_name
on conflict do nothing;

-- 4. Subjects: insert each distinct name that is not already present
--    (reuse by exact name keeps a shared subject and its search aliases).
insert into public.taxonomy_subjects (slug, name)
select v.slug, v.name from (values
  ('x80s-english', 'English'),
  ('x80s-urdu', 'Urdu'),
  ('x80s-mathematics', 'Mathematics'),
  ('x80s-phonics', 'Phonics'),
  ('x80s-pre-reading', 'Pre-Reading'),
  ('x80s-pre-writing', 'Pre-Writing'),
  ('x80s-vocabulary', 'Vocabulary'),
  ('x80s-communication-skills', 'Communication Skills'),
  ('x80s-general-knowledge', 'General Knowledge'),
  ('x80s-world-around-us', 'World Around Us'),
  ('x80s-science', 'Science'),
  ('x80s-environmental-awareness', 'Environmental Awareness'),
  ('x80s-islamic-studies-islamiat', 'Islamic Studies / Islamiat'),
  ('x80s-nazra-quran', 'Nazra Quran'),
  ('x80s-quran-studies', 'Quran Studies'),
  ('x80s-mother-tongue-regional-language', 'Mother Tongue / Regional Language'),
  ('x80s-health-hygiene', 'Health & Hygiene'),
  ('x80s-safety-education', 'Safety Education'),
  ('x80s-social-emotional-development', 'Social & Emotional Development'),
  ('x80s-moral-character-education', 'Moral & Character Education'),
  ('x80s-computer-skills', 'Computer Skills'),
  ('x80s-digital-literacy', 'Digital Literacy'),
  ('x80s-stem', 'STEM'),
  ('x80s-coding', 'Coding'),
  ('x80s-robotics', 'Robotics'),
  ('x80s-art-drawing', 'Art & Drawing'),
  ('x80s-creative-arts', 'Creative Arts'),
  ('x80s-craft', 'Craft'),
  ('x80s-music', 'Music'),
  ('x80s-rhymes-action-songs', 'Rhymes & Action Songs'),
  ('x80s-drama-role-play', 'Drama & Role Play'),
  ('x80s-physical-education', 'Physical Education'),
  ('x80s-gross-motor-skills', 'Gross Motor Skills'),
  ('x80s-fine-motor-skills', 'Fine Motor Skills'),
  ('x80s-practical-life-skills', 'Practical Life Skills'),
  ('x80s-life-skills', 'Life Skills'),
  ('x80s-montessori-activities', 'Montessori Activities'),
  ('x80s-sensory-learning', 'Sensory Learning'),
  ('x80s-play-based-learning', 'Play-Based Learning'),
  ('x80s-gardening', 'Gardening'),
  ('x80s-nature-study', 'Nature Study'),
  ('x80s-social-skills', 'Social Skills'),
  ('x80s-independence-skills', 'Independence Skills'),
  ('x80s-school-readiness', 'School Readiness'),
  ('x80s-handwriting-readiness', 'Handwriting Readiness'),
  ('x80s-creative-writing', 'Creative Writing'),
  ('x80s-public-speaking', 'Public Speaking'),
  ('x80s-confidence-building', 'Confidence Building'),
  ('x80s-general-science', 'General Science'),
  ('x80s-social-studies', 'Social Studies'),
  ('x80s-islamiat-islamic-studies', 'Islamiat / Islamic Studies'),
  ('x80s-quran-translation', 'Quran Translation'),
  ('x80s-ethics-religious-education', 'Ethics / Religious Education'),
  ('x80s-arabic', 'Arabic'),
  ('x80s-punjabi', 'Punjabi'),
  ('x80s-sindhi', 'Sindhi'),
  ('x80s-pashto', 'Pashto'),
  ('x80s-balochi', 'Balochi'),
  ('x80s-brahui', 'Brahui'),
  ('x80s-computer-science', 'Computer Science'),
  ('x80s-information-technology-ict', 'Information Technology / ICT'),
  ('x80s-programming', 'Programming'),
  ('x80s-artificial-intelligence', 'Artificial Intelligence'),
  ('x80s-environmental-studies', 'Environmental Studies'),
  ('x80s-fine-arts', 'Fine Arts'),
  ('x80s-drama-performing-arts', 'Drama & Performing Arts'),
  ('x80s-health-education', 'Health Education'),
  ('x80s-sports', 'Sports'),
  ('x80s-character-moral-education', 'Character & Moral Education'),
  ('x80s-personal-development', 'Personal Development'),
  ('x80s-handwriting', 'Handwriting'),
  ('x80s-reading', 'Reading'),
  ('x80s-english-grammar', 'English Grammar'),
  ('x80s-spelling', 'Spelling'),
  ('x80s-study-skills', 'Study Skills'),
  ('x80s-financial-literacy', 'Financial Literacy'),
  ('x80s-entrepreneurship', 'Entrepreneurship'),
  ('x80s-practical-skills', 'Practical Skills'),
  ('x80s-agriculture', 'Agriculture'),
  ('x80s-home-economics', 'Home Economics'),
  ('x80s-science-projects', 'Science Projects'),
  ('x80s-maker-education', 'Maker Education'),
  ('x80s-robotics-engineering', 'Robotics & Engineering'),
  ('x80s-3d-design-printing', '3D Design & Printing'),
  ('x80s-quran-studies-translation-of-holy-quran', 'Quran Studies / Translation of Holy Quran'),
  ('x80s-history', 'History'),
  ('x80s-geography', 'Geography'),
  ('x80s-regional-language', 'Regional Language'),
  ('x80s-persian', 'Persian'),
  ('x80s-english-literature', 'English Literature'),
  ('x80s-environmental-education', 'Environmental Education'),
  ('x80s-health-physical-education', 'Health & Physical Education'),
  ('x80s-technology', 'Technology'),
  ('x80s-electronics', 'Electronics'),
  ('x80s-library-reading', 'Library / Reading'),
  ('x80s-islamiyat-islamic-studies', 'Islamiyat / Islamic Studies'),
  ('x80s-pakistan-studies', 'Pakistan Studies'),
  ('x80s-economics', 'Economics'),
  ('x80s-civics', 'Civics'),
  ('x80s-education', 'Education'),
  ('x80s-drawing', 'Drawing'),
  ('x80s-information-technology', 'Information Technology'),
  ('x80s-punjabi-elective', 'Punjabi Elective'),
  ('x80s-arabic-elective', 'Arabic Elective'),
  ('x80s-persian-elective', 'Persian Elective'),
  ('x80s-civics-elective', 'Civics Elective'),
  ('x80s-economics-elective', 'Economics Elective'),
  ('x80s-education-elective', 'Education Elective'),
  ('x80s-history-elective', 'History Elective'),
  ('x80s-geography-elective', 'Geography Elective'),
  ('x80s-home-economics-elective', 'Home Economics Elective'),
  ('x80s-fine-arts-elective', 'Fine Arts Elective'),
  ('x80s-computer-science-elective', 'Computer Science Elective'),
  ('x80s-islamic-studies-elective', 'Islamic Studies Elective'),
  ('x80s-additional-mathematics', 'Additional Mathematics'),
  ('x80s-physics', 'Physics'),
  ('x80s-chemistry', 'Chemistry'),
  ('x80s-biology', 'Biology'),
  ('x80s-translation-of-the-holy-quran', 'Translation of the Holy Quran'),
  ('x80s-ethics', 'Ethics'),
  ('x80s-religious-education', 'Religious Education'),
  ('x80s-ict', 'ICT'),
  ('x80s-general-mathematics', 'General Mathematics'),
  ('x80s-combined-science', 'Combined Science'),
  ('x80s-co-ordinated-sciences', 'Co-ordinated Sciences'),
  ('x80s-islamiyat', 'Islamiyat'),
  ('x80s-accounting', 'Accounting'),
  ('x80s-business-studies', 'Business Studies'),
  ('x80s-sociology', 'Sociology'),
  ('x80s-environmental-management', 'Environmental Management'),
  ('x80s-art-design', 'Art & Design'),
  ('x80s-design-technology', 'Design & Technology'),
  ('x80s-literature-in-english', 'Literature in English'),
  ('x80s-global-perspectives', 'Global Perspectives'),
  ('x80s-english-language', 'English Language'),
  ('x80s-commerce', 'Commerce'),
  ('x80s-statistics', 'Statistics'),
  ('x80s-islamic-studies', 'Islamic Studies'),
  ('x80s-urdu-as-a-first-language', 'Urdu as a First Language'),
  ('x80s-urdu-as-a-second-language', 'Urdu as a Second Language'),
  ('x80s-food-nutrition', 'Food & Nutrition'),
  ('x80s-fashion-textiles', 'Fashion & Textiles'),
  ('x80s-travel-tourism', 'Travel & Tourism'),
  ('x80s-bangladesh-studies', 'Bangladesh Studies'),
  ('x80s-bengali', 'Bengali'),
  ('x80s-sinhala', 'Sinhala'),
  ('x80s-tamil', 'Tamil'),
  ('x80s-biblical-studies', 'Biblical Studies'),
  ('x80s-business', 'Business'),
  ('x80s-chinese-language', 'Chinese Language'),
  ('x80s-chinese-language-literature', 'Chinese Language & Literature'),
  ('x80s-classical-studies', 'Classical Studies'),
  ('x80s-digital-media-design', 'Digital Media & Design'),
  ('x80s-drama', 'Drama'),
  ('x80s-english-language-literature', 'English Language & Literature'),
  ('x80s-english-general-paper', 'English General Paper'),
  ('x80s-european-history', 'European History'),
  ('x80s-french-language', 'French Language'),
  ('x80s-french-language-literature', 'French Language & Literature'),
  ('x80s-german-language', 'German Language'),
  ('x80s-german-language-literature', 'German Language & Literature'),
  ('x80s-global-perspectives-research', 'Global Perspectives & Research'),
  ('x80s-hinduism', 'Hinduism'),
  ('x80s-international-history', 'International History'),
  ('x80s-law', 'Law'),
  ('x80s-marine-science', 'Marine Science'),
  ('x80s-further-mathematics', 'Further Mathematics'),
  ('x80s-media-studies', 'Media Studies'),
  ('x80s-portuguese', 'Portuguese'),
  ('x80s-psychology', 'Psychology'),
  ('x80s-spanish-language', 'Spanish Language'),
  ('x80s-spanish-language-literature', 'Spanish Language & Literature'),
  ('x80s-sport-physical-education', 'Sport & Physical Education'),
  ('x80s-thinking-skills', 'Thinking Skills'),
  ('x80s-urdu-language-literature', 'Urdu Language & Literature'),
  ('x80s-urdu-pakistan', 'Urdu – Pakistan'),
  ('x80s-us-history', 'US History'),
  ('x80s-environmental-science', 'Environmental Science'),
  ('x80s-economics-business', 'Economics & Business'),
  ('x80s-religious-studies', 'Religious Studies'),
  ('x80s-islamic-education-islamiat', 'Islamic Education / Islamiat'),
  ('x80s-history-of-islam', 'History of Islam'),
  ('x80s-history-of-muslim-india', 'History of Muslim India'),
  ('x80s-history-of-pakistan', 'History of Pakistan'),
  ('x80s-history-of-the-modern-world', 'History of the Modern World'),
  ('x80s-philosophy', 'Philosophy'),
  ('x80s-outlines-of-home-economics', 'Outlines of Home Economics'),
  ('x80s-saraiki', 'Saraiki'),
  ('x80s-urdu-advance', 'Urdu Advance'),
  ('x80s-english-elective', 'English Elective'),
  ('x80s-french', 'French'),
  ('x80s-german', 'German'),
  ('x80s-military-science', 'Military Science'),
  ('x80s-geology', 'Geology'),
  ('x80s-library-science', 'Library Science'),
  ('x80s-computer-science-entrepreneurship', 'Computer Science & Entrepreneurship'),
  ('x80s-nursing', 'Nursing'),
  ('x80s-commercial-practices', 'Commercial Practices'),
  ('x80s-applied-art', 'Applied Art'),
  ('x80s-child-development-family-living', 'Child Development & Family Living'),
  ('x80s-clothing-textile', 'Clothing & Textile'),
  ('x80s-finance', 'Finance'),
  ('x80s-management', 'Management'),
  ('x80s-marketing', 'Marketing'),
  ('x80s-human-resource-management', 'Human Resource Management'),
  ('x80s-political-science', 'Political Science'),
  ('x80s-international-relations', 'International Relations'),
  ('x80s-english-language-linguistics', 'English Language & Linguistics'),
  ('x80s-mass-communication', 'Mass Communication'),
  ('x80s-journalism', 'Journalism'),
  ('x80s-library-information-science', 'Library & Information Science'),
  ('x80s-social-work', 'Social Work'),
  ('x80s-public-administration', 'Public Administration'),
  ('x80s-food-science-technology', 'Food Science & Technology'),
  ('x80s-botany', 'Botany'),
  ('x80s-zoology', 'Zoology'),
  ('x80s-microbiology', 'Microbiology'),
  ('x80s-biotechnology', 'Biotechnology'),
  ('x80s-computer-programming', 'Computer Programming'),
  ('x80s-database-management', 'Database Management'),
  ('x80s-web-development', 'Web Development'),
  ('x80s-graphic-design', 'Graphic Design'),
  ('x80s-digital-marketing', 'Digital Marketing'),
  ('x80s-data-science', 'Data Science'),
  ('x80s-cyber-security', 'Cyber Security'),
  ('x80s-business-analytics', 'Business Analytics'),
  ('x80s-supply-chain-management', 'Supply Chain Management'),
  ('x80s-project-management', 'Project Management'),
  ('x80s-banking-finance', 'Banking & Finance'),
  ('x80s-islamic-banking-finance', 'Islamic Banking & Finance'),
  ('x80s-tourism-hospitality-management', 'Tourism & Hospitality Management'),
  ('x80s-special-education', 'Special Education'),
  ('x80s-early-childhood-education', 'Early Childhood Education'),
  ('x80s-public-health', 'Public Health'),
  ('x80s-human-nutrition-dietetics', 'Human Nutrition & Dietetics'),
  ('x80s-software-engineering', 'Software Engineering'),
  ('x80s-information-systems', 'Information Systems'),
  ('x80s-computer-engineering', 'Computer Engineering'),
  ('x80s-electrical-engineering', 'Electrical Engineering'),
  ('x80s-electronics-engineering', 'Electronics Engineering'),
  ('x80s-mechanical-engineering', 'Mechanical Engineering'),
  ('x80s-civil-engineering', 'Civil Engineering'),
  ('x80s-chemical-engineering', 'Chemical Engineering'),
  ('x80s-biomedical-engineering', 'Biomedical Engineering'),
  ('x80s-environmental-engineering', 'Environmental Engineering'),
  ('x80s-architecture', 'Architecture'),
  ('x80s-business-administration', 'Business Administration'),
  ('x80s-elementary-education', 'Elementary Education'),
  ('x80s-secondary-education', 'Secondary Education'),
  ('x80s-educational-leadership-management', 'Educational Leadership & Management'),
  ('x80s-applied-psychology', 'Applied Psychology'),
  ('x80s-urdu-literature', 'Urdu Literature'),
  ('x80s-development-studies', 'Development Studies'),
  ('x80s-peace-conflict-studies', 'Peace & Conflict Studies'),
  ('x80s-biochemistry', 'Biochemistry'),
  ('x80s-applied-mathematics', 'Applied Mathematics'),
  ('x80s-agronomy', 'Agronomy'),
  ('x80s-horticulture', 'Horticulture'),
  ('x80s-pharmacy', 'Pharmacy'),
  ('x80s-allied-health-sciences', 'Allied Health Sciences'),
  ('x80s-medical-laboratory-technology', 'Medical Laboratory Technology'),
  ('x80s-physiotherapy', 'Physiotherapy'),
  ('x80s-sports-sciences', 'Sports Sciences'),
  ('x80s-visual-arts', 'Visual Arts'),
  ('x80s-fashion-design', 'Fashion Design'),
  ('x80s-textile-design', 'Textile Design'),
  ('x80s-interior-design', 'Interior Design'),
  ('x80s-hotel-management', 'Hotel Management'),
  ('x80s-aviation-management', 'Aviation Management'),
  ('x80s-media-communication', 'Media & Communication'),
  ('x80s-film-television', 'Film & Television'),
  ('x80s-theatre-performing-arts', 'Theatre & Performing Arts'),
  ('x80s-islamic-economics', 'Islamic Economics'),
  ('x80s-actuarial-science', 'Actuarial Science'),
  ('x80s-operations-research', 'Operations Research'),
  ('x80s-artificial-intelligence-robotics', 'Artificial Intelligence & Robotics'),
  ('x80s-blockchain-technology', 'Blockchain Technology'),
  ('x80s-cloud-computing', 'Cloud Computing'),
  ('x80s-mobile-application-development', 'Mobile Application Development'),
  ('x80s-game-development', 'Game Development'),
  ('x80s-e-commerce', 'E-Commerce'),
  ('x80s-fintech', 'FinTech'),
  ('x80s-renewable-energy', 'Renewable Energy'),
  ('x80s-energy-engineering', 'Energy Engineering'),
  ('x80s-telecommunication-engineering', 'Telecommunication Engineering'),
  ('x80s-mechatronics-engineering', 'Mechatronics Engineering'),
  ('x80s-robotics-engineering-2', 'Robotics Engineering'),
  ('x80s-gre-preparation', 'GRE Preparation'),
  ('x80s-gmat-preparation', 'GMAT Preparation'),
  ('x80s-ielts-preparation', 'IELTS Preparation'),
  ('x80s-toefl-preparation', 'TOEFL Preparation'),
  ('x80s-pte-academic-preparation', 'PTE Academic Preparation'),
  ('x80s-mdcat-preparation', 'MDCAT Preparation'),
  ('x80s-ecat-preparation', 'ECAT Preparation'),
  ('x80s-net-preparation', 'NET Preparation'),
  ('x80s-fast-nu-admission-test-preparation', 'FAST-NU Admission Test Preparation'),
  ('x80s-giki-admission-test-preparation', 'GIKI Admission Test Preparation'),
  ('x80s-comsats-admission-test-preparation', 'COMSATS Admission Test Preparation'),
  ('x80s-lums-admission-test-preparation', 'LUMS Admission Test Preparation'),
  ('x80s-nts-test-preparation', 'NTS Test Preparation'),
  ('x80s-nat-preparation', 'NAT Preparation'),
  ('x80s-gat-general-preparation', 'GAT General Preparation'),
  ('x80s-gat-subject-preparation', 'GAT Subject Preparation'),
  ('x80s-etea-test-preparation', 'ETEA Test Preparation'),
  ('x80s-ecat-engineering-entry-test-preparation', 'ECAT Engineering Entry Test Preparation'),
  ('x80s-university-admission-test-preparation', 'University Admission Test Preparation'),
  ('x80s-medical-entry-test-preparation', 'Medical Entry Test Preparation'),
  ('x80s-engineering-entry-test-preparation', 'Engineering Entry Test Preparation'),
  ('x80s-law-admission-test-lat-preparation', 'Law Admission Test (LAT) Preparation'),
  ('x80s-law-gat-preparation', 'Law GAT Preparation'),
  ('x80s-css-preparation', 'CSS Preparation'),
  ('x80s-pms-preparation', 'PMS Preparation'),
  ('x80s-fpsc-test-preparation', 'FPSC Test Preparation'),
  ('x80s-ppsc-test-preparation', 'PPSC Test Preparation'),
  ('x80s-spsc-test-preparation', 'SPSC Test Preparation'),
  ('x80s-kppsc-test-preparation', 'KPPSC Test Preparation'),
  ('x80s-bpsc-test-preparation', 'BPSC Test Preparation'),
  ('x80s-ajkpsc-test-preparation', 'AJKPSC Test Preparation'),
  ('x80s-nts-recruitment-test-preparation', 'NTS Recruitment Test Preparation'),
  ('x80s-fpsc-competitive-exam-preparation', 'FPSC Competitive Exam Preparation'),
  ('x80s-police-recruitment-test-preparation', 'Police Recruitment Test Preparation'),
  ('x80s-armed-forces-test-preparation', 'Armed Forces Test Preparation'),
  ('x80s-issb-preparation', 'ISSB Preparation'),
  ('x80s-pakistan-army-initial-test-preparation', 'Pakistan Army Initial Test Preparation'),
  ('x80s-pakistan-navy-test-preparation', 'Pakistan Navy Test Preparation'),
  ('x80s-pakistan-air-force-test-preparation', 'Pakistan Air Force Test Preparation'),
  ('x80s-cadet-college-entry-test-preparation', 'Cadet College Entry Test Preparation'),
  ('x80s-military-college-entry-test-preparation', 'Military College Entry Test Preparation'),
  ('x80s-scholarship-test-preparation', 'Scholarship Test Preparation'),
  ('x80s-school-admission-test-preparation', 'School Admission Test Preparation'),
  ('x80s-college-admission-test-preparation', 'College Admission Test Preparation'),
  ('x80s-university-entrance-test-preparation', 'University Entrance Test Preparation'),
  ('x80s-english-proficiency-test-preparation', 'English Proficiency Test Preparation'),
  ('x80s-general-aptitude-test-preparation', 'General Aptitude Test Preparation'),
  ('x80s-verbal-reasoning', 'Verbal Reasoning'),
  ('x80s-quantitative-reasoning', 'Quantitative Reasoning'),
  ('x80s-logical-reasoning', 'Logical Reasoning'),
  ('x80s-analytical-reasoning', 'Analytical Reasoning'),
  ('x80s-non-verbal-reasoning', 'Non-Verbal Reasoning'),
  ('x80s-iq-test-preparation', 'IQ Test Preparation'),
  ('x80s-general-knowledge-test-preparation', 'General Knowledge Test Preparation'),
  ('x80s-current-affairs-test-preparation', 'Current Affairs Test Preparation'),
  ('x80s-subject-specialist-test-preparation', 'Subject Specialist Test Preparation'),
  ('x80s-teaching-recruitment-test-preparation', 'Teaching Recruitment Test Preparation'),
  ('x80s-educator-test-preparation', 'Educator Test Preparation'),
  ('x80s-banking-test-preparation', 'Banking Test Preparation'),
  ('x80s-accounting-finance-test-preparation', 'Accounting & Finance Test Preparation'),
  ('x80s-computer-based-test-preparation', 'Computer-Based Test Preparation'),
  ('x80s-typing-test-preparation', 'Typing Test Preparation'),
  ('x80s-driving-license-test-preparation', 'Driving License Test Preparation'),
  ('x80s-vocational-test-preparation', 'Vocational Test Preparation'),
  ('x80s-quranic-studies', 'Quranic Studies'),
  ('x80s-hadith-studies', 'Hadith Studies'),
  ('x80s-comparative-religion', 'Comparative Religion'),
  ('x80s-teacher-education', 'Teacher Education'),
  ('x80s-educational-psychology', 'Educational Psychology'),
  ('x80s-curriculum-instruction', 'Curriculum & Instruction'),
  ('x80s-educational-technology', 'Educational Technology'),
  ('x80s-educational-planning-management', 'Educational Planning & Management'),
  ('x80s-clinical-psychology', 'Clinical Psychology'),
  ('x80s-management-sciences', 'Management Sciences'),
  ('x80s-plant-sciences', 'Plant Sciences'),
  ('x80s-animal-sciences', 'Animal Sciences'),
  ('x80s-veterinary-sciences', 'Veterinary Sciences'),
  ('x80s-epidemiology', 'Epidemiology'),
  ('x80s-pharmaceutical-sciences', 'Pharmaceutical Sciences'),
  ('x80s-pharmacology', 'Pharmacology'),
  ('x80s-medical-laboratory-sciences', 'Medical Laboratory Sciences'),
  ('x80s-gender-studies', 'Gender Studies'),
  ('x80s-international-development', 'International Development'),
  ('x80s-defence-strategic-studies', 'Defence & Strategic Studies'),
  ('x80s-defence-studies', 'Defence Studies'),
  ('x80s-criminology', 'Criminology'),
  ('x80s-anthropology', 'Anthropology'),
  ('x80s-archaeology', 'Archaeology'),
  ('x80s-economics-finance', 'Economics & Finance'),
  ('x80s-islamic-finance', 'Islamic Finance'),
  ('x80s-data-analytics', 'Data Analytics'),
  ('x80s-energy-studies', 'Energy Studies'),
  ('x80s-climate-change', 'Climate Change'),
  ('x80s-biotechnology-genetic-engineering', 'Biotechnology & Genetic Engineering'),
  ('x80s-molecular-biology', 'Molecular Biology'),
  ('x80s-genetics', 'Genetics'),
  ('x80s-bioinformatics', 'Bioinformatics'),
  ('x80s-neuroscience', 'Neuroscience'),
  ('x80s-nanotechnology', 'Nanotechnology'),
  ('x80s-materials-science', 'Materials Science'),
  ('x80s-computational-physics', 'Computational Physics'),
  ('x80s-computational-mathematics', 'Computational Mathematics'),
  ('x80s-computational-biology', 'Computational Biology'),
  ('x80s-remote-sensing-gis', 'Remote Sensing & GIS'),
  ('x80s-international-business', 'International Business'),
  ('x80s-operations-management', 'Operations Management'),
  ('x80s-organizational-psychology', 'Organizational Psychology'),
  ('x80s-organizational-behavior', 'Organizational Behavior'),
  ('x80s-leadership-management', 'Leadership & Management'),
  ('x80s-hifzul-quran', 'Hifzul Quran'),
  ('x80s-translation-of-quran', 'Translation of Quran'),
  ('x80s-chess', 'Chess'),
  ('x80s-ludo', 'Ludo'),
  ('x80s-carrom', 'Carrom'),
  ('x80s-scrabble', 'Scrabble'),
  ('x80s-rubik-s-cube', 'Rubik''s Cube'),
  ('x80s-darts', 'Darts'),
  ('x80s-table-tennis', 'Table Tennis'),
  ('x80s-badminton', 'Badminton'),
  ('x80s-basketball-skills', 'Basketball Skills'),
  ('x80s-football-skills', 'Football Skills'),
  ('x80s-cricket-skills', 'Cricket Skills'),
  ('x80s-tennis-skills', 'Tennis Skills'),
  ('x80s-hockey-skills', 'Hockey Skills'),
  ('x80s-futsal-skills', 'Futsal Skills'),
  ('x80s-volleyball-skills', 'Volleyball Skills'),
  ('x80s-athletics', 'Athletics'),
  ('x80s-running', 'Running'),
  ('x80s-fitness-training', 'Fitness Training'),
  ('x80s-physical-fitness', 'Physical Fitness'),
  ('x80s-yoga', 'Yoga'),
  ('x80s-gymnastics', 'Gymnastics'),
  ('x80s-skipping', 'Skipping'),
  ('x80s-cycling', 'Cycling'),
  ('x80s-roller-skating', 'Roller Skating'),
  ('x80s-skating', 'Skating'),
  ('x80s-karate', 'Karate'),
  ('x80s-taekwondo', 'Taekwondo'),
  ('x80s-judo', 'Judo'),
  ('x80s-martial-arts', 'Martial Arts'),
  ('x80s-self-defense', 'Self-Defense'),
  ('x80s-boxing-fitness', 'Boxing Fitness'),
  ('x80s-wrestling', 'Wrestling'),
  ('x80s-archery', 'Archery'),
  ('x80s-dance', 'Dance'),
  ('x80s-ballet', 'Ballet'),
  ('x80s-swimming-theory-dry-training', 'Swimming Theory & Dry Training'),
  ('x80s-sports-skills-development', 'Sports Skills Development'),
  ('x80s-motor-skills-development', 'Motor Skills Development'),
  ('x80s-coordination-training', 'Coordination Training'),
  ('x80s-balance-training', 'Balance Training'),
  ('x80s-agility-training', 'Agility Training'),
  ('x80s-speed-reaction-training', 'Speed & Reaction Training'),
  ('x80s-strength-conditioning', 'Strength & Conditioning'),
  ('x80s-endurance-training', 'Endurance Training'),
  ('x80s-sports-fitness', 'Sports Fitness'),
  ('x80s-sports-psychology', 'Sports Psychology'),
  ('x80s-sports-strategy-tactics', 'Sports Strategy & Tactics'),
  ('x80s-referee-rules-training', 'Referee & Rules Training'),
  ('x80s-e-sports', 'E-Sports'),
  ('x80s-gaming-skills', 'Gaming Skills'),
  ('x80s-mind-games', 'Mind Games'),
  ('x80s-board-games', 'Board Games'),
  ('x80s-language', 'Language'),
  ('x80s-arts', 'Arts'),
  ('x80s-personal-social-physical-education', 'Personal, Social & Physical Education'),
  ('x80s-language-literature', 'Language & Literature'),
  ('x80s-language-acquisition', 'Language Acquisition'),
  ('x80s-individuals-societies', 'Individuals & Societies'),
  ('x80s-sciences', 'Sciences'),
  ('x80s-physical-health-education', 'Physical & Health Education'),
  ('x80s-design', 'Design'),
  ('x80s-language-a-literature', 'Language A: Literature'),
  ('x80s-language-a-language-literature', 'Language A: Language & Literature'),
  ('x80s-literature-performance', 'Literature & Performance'),
  ('x80s-language-b', 'Language B'),
  ('x80s-language-ab-initio', 'Language ab initio'),
  ('x80s-classical-languages', 'Classical Languages'),
  ('x80s-business-management', 'Business Management'),
  ('x80s-digital-society', 'Digital Society'),
  ('x80s-global-politics', 'Global Politics'),
  ('x80s-social-cultural-anthropology', 'Social & Cultural Anthropology'),
  ('x80s-world-religions', 'World Religions'),
  ('x80s-design-technology-2', 'Design Technology'),
  ('x80s-environmental-systems-societies', 'Environmental Systems & Societies'),
  ('x80s-sports-exercise-health-science', 'Sports, Exercise & Health Science'),
  ('x80s-mathematics-analysis-approaches', 'Mathematics: Analysis & Approaches'),
  ('x80s-mathematics-applications-interpretation', 'Mathematics: Applications & Interpretation'),
  ('x80s-film', 'Film'),
  ('x80s-theatre', 'Theatre'),
  ('x80s-theory-of-knowledge', 'Theory of Knowledge'),
  ('x80s-extended-essay', 'Extended Essay'),
  ('x80s-creativity-activity-service', 'Creativity, Activity, Service')
) as v(slug, name)
where not exists (select 1 from public.taxonomy_subjects s where s.name = v.name)
on conflict do nothing;

-- 5. Master: 1,475 (grade, subject) combinations. category from the grade,
--    subject by exact name (names are unique). leaf_type 'subject' — the
--    new dataset has no level-leaves.
insert into public.taxonomy_master (category_slug, level_slug, subject_slug, leaf_type)
select l.category_slug, l.slug,
  (select s.slug from public.taxonomy_subjects s where s.name = v.subject_name limit 1),
  'subject'
from (values
  ('x80g-1', 'English'),
  ('x80g-1', 'Urdu'),
  ('x80g-1', 'Mathematics'),
  ('x80g-1', 'Phonics'),
  ('x80g-1', 'Pre-Reading'),
  ('x80g-1', 'Pre-Writing'),
  ('x80g-1', 'Vocabulary'),
  ('x80g-1', 'Communication Skills'),
  ('x80g-1', 'General Knowledge'),
  ('x80g-1', 'World Around Us'),
  ('x80g-1', 'Science'),
  ('x80g-1', 'Environmental Awareness'),
  ('x80g-1', 'Islamic Studies / Islamiat'),
  ('x80g-1', 'Nazra Quran'),
  ('x80g-1', 'Quran Studies'),
  ('x80g-1', 'Mother Tongue / Regional Language'),
  ('x80g-1', 'Health & Hygiene'),
  ('x80g-1', 'Safety Education'),
  ('x80g-1', 'Social & Emotional Development'),
  ('x80g-1', 'Moral & Character Education'),
  ('x80g-1', 'Computer Skills'),
  ('x80g-1', 'Digital Literacy'),
  ('x80g-1', 'STEM'),
  ('x80g-1', 'Coding'),
  ('x80g-1', 'Robotics'),
  ('x80g-1', 'Art & Drawing'),
  ('x80g-1', 'Creative Arts'),
  ('x80g-1', 'Craft'),
  ('x80g-1', 'Music'),
  ('x80g-1', 'Rhymes & Action Songs'),
  ('x80g-1', 'Drama & Role Play'),
  ('x80g-1', 'Physical Education'),
  ('x80g-1', 'Gross Motor Skills'),
  ('x80g-1', 'Fine Motor Skills'),
  ('x80g-1', 'Practical Life Skills'),
  ('x80g-1', 'Life Skills'),
  ('x80g-1', 'Montessori Activities'),
  ('x80g-1', 'Sensory Learning'),
  ('x80g-1', 'Play-Based Learning'),
  ('x80g-1', 'Gardening'),
  ('x80g-1', 'Nature Study'),
  ('x80g-1', 'Social Skills'),
  ('x80g-1', 'Independence Skills'),
  ('x80g-1', 'School Readiness'),
  ('x80g-1', 'Handwriting Readiness'),
  ('x80g-1', 'Creative Writing'),
  ('x80g-1', 'Public Speaking'),
  ('x80g-1', 'Confidence Building'),
  ('x80g-2', 'English'),
  ('x80g-2', 'Urdu'),
  ('x80g-2', 'Mathematics'),
  ('x80g-2', 'Phonics'),
  ('x80g-2', 'Pre-Reading'),
  ('x80g-2', 'Pre-Writing'),
  ('x80g-2', 'Vocabulary'),
  ('x80g-2', 'Communication Skills'),
  ('x80g-2', 'General Knowledge'),
  ('x80g-2', 'World Around Us'),
  ('x80g-2', 'Science'),
  ('x80g-2', 'Environmental Awareness'),
  ('x80g-2', 'Islamic Studies / Islamiat'),
  ('x80g-2', 'Nazra Quran'),
  ('x80g-2', 'Quran Studies'),
  ('x80g-2', 'Mother Tongue / Regional Language'),
  ('x80g-2', 'Health & Hygiene'),
  ('x80g-2', 'Safety Education'),
  ('x80g-2', 'Social & Emotional Development'),
  ('x80g-2', 'Moral & Character Education'),
  ('x80g-2', 'Computer Skills'),
  ('x80g-2', 'Digital Literacy'),
  ('x80g-2', 'STEM'),
  ('x80g-2', 'Coding'),
  ('x80g-2', 'Robotics'),
  ('x80g-2', 'Art & Drawing'),
  ('x80g-2', 'Creative Arts'),
  ('x80g-2', 'Craft'),
  ('x80g-2', 'Music'),
  ('x80g-2', 'Rhymes & Action Songs'),
  ('x80g-2', 'Drama & Role Play'),
  ('x80g-2', 'Physical Education'),
  ('x80g-2', 'Gross Motor Skills'),
  ('x80g-2', 'Fine Motor Skills'),
  ('x80g-2', 'Practical Life Skills'),
  ('x80g-2', 'Life Skills'),
  ('x80g-2', 'Montessori Activities'),
  ('x80g-2', 'Sensory Learning'),
  ('x80g-2', 'Play-Based Learning'),
  ('x80g-2', 'Gardening'),
  ('x80g-2', 'Nature Study'),
  ('x80g-2', 'Social Skills'),
  ('x80g-2', 'Independence Skills'),
  ('x80g-2', 'School Readiness'),
  ('x80g-2', 'Handwriting Readiness'),
  ('x80g-2', 'Creative Writing'),
  ('x80g-2', 'Public Speaking'),
  ('x80g-2', 'Confidence Building'),
  ('x80g-3', 'English'),
  ('x80g-3', 'Urdu'),
  ('x80g-3', 'Mathematics'),
  ('x80g-3', 'Phonics'),
  ('x80g-3', 'Pre-Reading'),
  ('x80g-3', 'Pre-Writing'),
  ('x80g-3', 'Vocabulary'),
  ('x80g-3', 'Communication Skills'),
  ('x80g-3', 'General Knowledge'),
  ('x80g-3', 'World Around Us'),
  ('x80g-3', 'Science'),
  ('x80g-3', 'Environmental Awareness'),
  ('x80g-3', 'Islamic Studies / Islamiat'),
  ('x80g-3', 'Nazra Quran'),
  ('x80g-3', 'Quran Studies'),
  ('x80g-3', 'Mother Tongue / Regional Language'),
  ('x80g-3', 'Health & Hygiene'),
  ('x80g-3', 'Safety Education'),
  ('x80g-3', 'Social & Emotional Development'),
  ('x80g-3', 'Moral & Character Education'),
  ('x80g-3', 'Computer Skills'),
  ('x80g-3', 'Digital Literacy'),
  ('x80g-3', 'STEM'),
  ('x80g-3', 'Coding'),
  ('x80g-3', 'Robotics'),
  ('x80g-3', 'Art & Drawing'),
  ('x80g-3', 'Creative Arts'),
  ('x80g-3', 'Craft'),
  ('x80g-3', 'Music'),
  ('x80g-3', 'Rhymes & Action Songs'),
  ('x80g-3', 'Drama & Role Play'),
  ('x80g-3', 'Physical Education'),
  ('x80g-3', 'Gross Motor Skills'),
  ('x80g-3', 'Fine Motor Skills'),
  ('x80g-3', 'Practical Life Skills'),
  ('x80g-3', 'Life Skills'),
  ('x80g-3', 'Montessori Activities'),
  ('x80g-3', 'Sensory Learning'),
  ('x80g-3', 'Play-Based Learning'),
  ('x80g-3', 'Gardening'),
  ('x80g-3', 'Nature Study'),
  ('x80g-3', 'Social Skills'),
  ('x80g-3', 'Independence Skills'),
  ('x80g-3', 'School Readiness'),
  ('x80g-3', 'Handwriting Readiness'),
  ('x80g-3', 'Creative Writing'),
  ('x80g-3', 'Public Speaking'),
  ('x80g-3', 'Confidence Building'),
  ('x80g-4', 'English'),
  ('x80g-4', 'Urdu'),
  ('x80g-4', 'Mathematics'),
  ('x80g-4', 'General Science'),
  ('x80g-4', 'General Knowledge'),
  ('x80g-4', 'Social Studies'),
  ('x80g-4', 'Islamiat / Islamic Studies'),
  ('x80g-4', 'Quran Studies'),
  ('x80g-4', 'Nazra Quran'),
  ('x80g-4', 'Quran Translation'),
  ('x80g-4', 'Ethics / Religious Education'),
  ('x80g-4', 'Arabic'),
  ('x80g-4', 'Punjabi'),
  ('x80g-4', 'Sindhi'),
  ('x80g-4', 'Pashto'),
  ('x80g-4', 'Balochi'),
  ('x80g-4', 'Brahui'),
  ('x80g-4', 'Computer Science'),
  ('x80g-4', 'Information Technology / ICT'),
  ('x80g-4', 'Digital Literacy'),
  ('x80g-4', 'Coding'),
  ('x80g-4', 'Programming'),
  ('x80g-4', 'STEM'),
  ('x80g-4', 'Robotics'),
  ('x80g-4', 'Artificial Intelligence'),
  ('x80g-4', 'Environmental Studies'),
  ('x80g-4', 'Art & Drawing'),
  ('x80g-4', 'Fine Arts'),
  ('x80g-4', 'Craft'),
  ('x80g-4', 'Music'),
  ('x80g-4', 'Drama & Performing Arts'),
  ('x80g-4', 'Physical Education'),
  ('x80g-4', 'Health Education'),
  ('x80g-4', 'Sports'),
  ('x80g-4', 'Life Skills'),
  ('x80g-4', 'Character & Moral Education'),
  ('x80g-4', 'Personal Development'),
  ('x80g-4', 'Handwriting'),
  ('x80g-4', 'Reading'),
  ('x80g-4', 'Phonics'),
  ('x80g-4', 'English Grammar'),
  ('x80g-4', 'Creative Writing'),
  ('x80g-4', 'Spelling'),
  ('x80g-4', 'Vocabulary'),
  ('x80g-4', 'Communication Skills'),
  ('x80g-4', 'Public Speaking'),
  ('x80g-4', 'Study Skills'),
  ('x80g-4', 'Financial Literacy'),
  ('x80g-4', 'Entrepreneurship'),
  ('x80g-4', 'Practical Skills'),
  ('x80g-4', 'Agriculture'),
  ('x80g-4', 'Gardening'),
  ('x80g-4', 'Home Economics'),
  ('x80g-4', 'Science Projects'),
  ('x80g-4', 'Maker Education'),
  ('x80g-4', 'Robotics & Engineering'),
  ('x80g-4', '3D Design & Printing'),
  ('x80g-5', 'English'),
  ('x80g-5', 'Urdu'),
  ('x80g-5', 'Mathematics'),
  ('x80g-5', 'General Science'),
  ('x80g-5', 'General Knowledge'),
  ('x80g-5', 'Social Studies'),
  ('x80g-5', 'Islamiat / Islamic Studies'),
  ('x80g-5', 'Quran Studies'),
  ('x80g-5', 'Nazra Quran'),
  ('x80g-5', 'Quran Translation'),
  ('x80g-5', 'Ethics / Religious Education'),
  ('x80g-5', 'Arabic'),
  ('x80g-5', 'Punjabi'),
  ('x80g-5', 'Sindhi'),
  ('x80g-5', 'Pashto'),
  ('x80g-5', 'Balochi'),
  ('x80g-5', 'Brahui'),
  ('x80g-5', 'Computer Science'),
  ('x80g-5', 'Information Technology / ICT'),
  ('x80g-5', 'Digital Literacy'),
  ('x80g-5', 'Coding'),
  ('x80g-5', 'Programming'),
  ('x80g-5', 'STEM'),
  ('x80g-5', 'Robotics'),
  ('x80g-5', 'Artificial Intelligence'),
  ('x80g-5', 'Environmental Studies'),
  ('x80g-5', 'Art & Drawing'),
  ('x80g-5', 'Fine Arts'),
  ('x80g-5', 'Craft'),
  ('x80g-5', 'Music'),
  ('x80g-5', 'Drama & Performing Arts'),
  ('x80g-5', 'Physical Education'),
  ('x80g-5', 'Health Education'),
  ('x80g-5', 'Sports'),
  ('x80g-5', 'Life Skills'),
  ('x80g-5', 'Character & Moral Education'),
  ('x80g-5', 'Personal Development'),
  ('x80g-5', 'Handwriting'),
  ('x80g-5', 'Reading'),
  ('x80g-5', 'Phonics'),
  ('x80g-5', 'English Grammar'),
  ('x80g-5', 'Creative Writing'),
  ('x80g-5', 'Spelling'),
  ('x80g-5', 'Vocabulary'),
  ('x80g-5', 'Communication Skills'),
  ('x80g-5', 'Public Speaking'),
  ('x80g-5', 'Study Skills'),
  ('x80g-5', 'Financial Literacy'),
  ('x80g-5', 'Entrepreneurship'),
  ('x80g-5', 'Practical Skills'),
  ('x80g-5', 'Agriculture'),
  ('x80g-5', 'Gardening'),
  ('x80g-5', 'Home Economics'),
  ('x80g-5', 'Science Projects'),
  ('x80g-5', 'Maker Education'),
  ('x80g-5', 'Robotics & Engineering'),
  ('x80g-5', '3D Design & Printing'),
  ('x80g-6', 'English'),
  ('x80g-6', 'Urdu'),
  ('x80g-6', 'Mathematics'),
  ('x80g-6', 'General Science'),
  ('x80g-6', 'General Knowledge'),
  ('x80g-6', 'Social Studies'),
  ('x80g-6', 'Islamiat / Islamic Studies'),
  ('x80g-6', 'Quran Studies'),
  ('x80g-6', 'Nazra Quran'),
  ('x80g-6', 'Quran Translation'),
  ('x80g-6', 'Ethics / Religious Education'),
  ('x80g-6', 'Arabic'),
  ('x80g-6', 'Punjabi'),
  ('x80g-6', 'Sindhi'),
  ('x80g-6', 'Pashto'),
  ('x80g-6', 'Balochi'),
  ('x80g-6', 'Brahui'),
  ('x80g-6', 'Computer Science'),
  ('x80g-6', 'Information Technology / ICT'),
  ('x80g-6', 'Digital Literacy'),
  ('x80g-6', 'Coding'),
  ('x80g-6', 'Programming'),
  ('x80g-6', 'STEM'),
  ('x80g-6', 'Robotics'),
  ('x80g-6', 'Artificial Intelligence'),
  ('x80g-6', 'Environmental Studies'),
  ('x80g-6', 'Art & Drawing'),
  ('x80g-6', 'Fine Arts'),
  ('x80g-6', 'Craft'),
  ('x80g-6', 'Music'),
  ('x80g-6', 'Drama & Performing Arts'),
  ('x80g-6', 'Physical Education'),
  ('x80g-6', 'Health Education'),
  ('x80g-6', 'Sports'),
  ('x80g-6', 'Life Skills'),
  ('x80g-6', 'Character & Moral Education'),
  ('x80g-6', 'Personal Development'),
  ('x80g-6', 'Handwriting'),
  ('x80g-6', 'Reading'),
  ('x80g-6', 'Phonics'),
  ('x80g-6', 'English Grammar'),
  ('x80g-6', 'Creative Writing'),
  ('x80g-6', 'Spelling'),
  ('x80g-6', 'Vocabulary'),
  ('x80g-6', 'Communication Skills'),
  ('x80g-6', 'Public Speaking'),
  ('x80g-6', 'Study Skills'),
  ('x80g-6', 'Financial Literacy'),
  ('x80g-6', 'Entrepreneurship'),
  ('x80g-6', 'Practical Skills'),
  ('x80g-6', 'Agriculture'),
  ('x80g-6', 'Gardening'),
  ('x80g-6', 'Home Economics'),
  ('x80g-6', 'Science Projects'),
  ('x80g-6', 'Maker Education'),
  ('x80g-6', 'Robotics & Engineering'),
  ('x80g-6', '3D Design & Printing'),
  ('x80g-7', 'English'),
  ('x80g-7', 'Urdu'),
  ('x80g-7', 'Mathematics'),
  ('x80g-7', 'General Science'),
  ('x80g-7', 'General Knowledge'),
  ('x80g-7', 'Social Studies'),
  ('x80g-7', 'Islamiat / Islamic Studies'),
  ('x80g-7', 'Quran Studies'),
  ('x80g-7', 'Nazra Quran'),
  ('x80g-7', 'Quran Translation'),
  ('x80g-7', 'Ethics / Religious Education'),
  ('x80g-7', 'Arabic'),
  ('x80g-7', 'Punjabi'),
  ('x80g-7', 'Sindhi'),
  ('x80g-7', 'Pashto'),
  ('x80g-7', 'Balochi'),
  ('x80g-7', 'Brahui'),
  ('x80g-7', 'Computer Science'),
  ('x80g-7', 'Information Technology / ICT'),
  ('x80g-7', 'Digital Literacy'),
  ('x80g-7', 'Coding'),
  ('x80g-7', 'Programming'),
  ('x80g-7', 'STEM'),
  ('x80g-7', 'Robotics'),
  ('x80g-7', 'Artificial Intelligence'),
  ('x80g-7', 'Environmental Studies'),
  ('x80g-7', 'Art & Drawing'),
  ('x80g-7', 'Fine Arts'),
  ('x80g-7', 'Craft'),
  ('x80g-7', 'Music'),
  ('x80g-7', 'Drama & Performing Arts'),
  ('x80g-7', 'Physical Education'),
  ('x80g-7', 'Health Education'),
  ('x80g-7', 'Sports'),
  ('x80g-7', 'Life Skills'),
  ('x80g-7', 'Character & Moral Education'),
  ('x80g-7', 'Personal Development'),
  ('x80g-7', 'Handwriting'),
  ('x80g-7', 'Reading'),
  ('x80g-7', 'Phonics'),
  ('x80g-7', 'English Grammar'),
  ('x80g-7', 'Creative Writing'),
  ('x80g-7', 'Spelling'),
  ('x80g-7', 'Vocabulary'),
  ('x80g-7', 'Communication Skills'),
  ('x80g-7', 'Public Speaking'),
  ('x80g-7', 'Study Skills'),
  ('x80g-7', 'Financial Literacy'),
  ('x80g-7', 'Entrepreneurship'),
  ('x80g-7', 'Practical Skills'),
  ('x80g-7', 'Agriculture'),
  ('x80g-7', 'Gardening'),
  ('x80g-7', 'Home Economics'),
  ('x80g-7', 'Science Projects'),
  ('x80g-7', 'Maker Education'),
  ('x80g-7', 'Robotics & Engineering'),
  ('x80g-7', '3D Design & Printing'),
  ('x80g-8', 'English'),
  ('x80g-8', 'Urdu'),
  ('x80g-8', 'Mathematics'),
  ('x80g-8', 'General Science'),
  ('x80g-8', 'General Knowledge'),
  ('x80g-8', 'Social Studies'),
  ('x80g-8', 'Islamiat / Islamic Studies'),
  ('x80g-8', 'Quran Studies'),
  ('x80g-8', 'Nazra Quran'),
  ('x80g-8', 'Quran Translation'),
  ('x80g-8', 'Ethics / Religious Education'),
  ('x80g-8', 'Arabic'),
  ('x80g-8', 'Punjabi'),
  ('x80g-8', 'Sindhi'),
  ('x80g-8', 'Pashto'),
  ('x80g-8', 'Balochi'),
  ('x80g-8', 'Brahui'),
  ('x80g-8', 'Computer Science'),
  ('x80g-8', 'Information Technology / ICT'),
  ('x80g-8', 'Digital Literacy'),
  ('x80g-8', 'Coding'),
  ('x80g-8', 'Programming'),
  ('x80g-8', 'STEM'),
  ('x80g-8', 'Robotics'),
  ('x80g-8', 'Artificial Intelligence'),
  ('x80g-8', 'Environmental Studies'),
  ('x80g-8', 'Art & Drawing'),
  ('x80g-8', 'Fine Arts'),
  ('x80g-8', 'Craft'),
  ('x80g-8', 'Music'),
  ('x80g-8', 'Drama & Performing Arts'),
  ('x80g-8', 'Physical Education'),
  ('x80g-8', 'Health Education'),
  ('x80g-8', 'Sports'),
  ('x80g-8', 'Life Skills'),
  ('x80g-8', 'Character & Moral Education'),
  ('x80g-8', 'Personal Development'),
  ('x80g-8', 'Handwriting'),
  ('x80g-8', 'Reading'),
  ('x80g-8', 'Phonics'),
  ('x80g-8', 'English Grammar'),
  ('x80g-8', 'Creative Writing'),
  ('x80g-8', 'Spelling'),
  ('x80g-8', 'Vocabulary'),
  ('x80g-8', 'Communication Skills'),
  ('x80g-8', 'Public Speaking'),
  ('x80g-8', 'Study Skills'),
  ('x80g-8', 'Financial Literacy'),
  ('x80g-8', 'Entrepreneurship'),
  ('x80g-8', 'Practical Skills'),
  ('x80g-8', 'Agriculture'),
  ('x80g-8', 'Gardening'),
  ('x80g-8', 'Home Economics'),
  ('x80g-8', 'Science Projects'),
  ('x80g-8', 'Maker Education'),
  ('x80g-8', 'Robotics & Engineering'),
  ('x80g-8', '3D Design & Printing'),
  ('x80g-9', 'English'),
  ('x80g-9', 'Urdu'),
  ('x80g-9', 'Mathematics'),
  ('x80g-9', 'General Science'),
  ('x80g-9', 'Computer Science'),
  ('x80g-9', 'Islamiat / Islamic Studies'),
  ('x80g-9', 'Quran Studies / Translation of Holy Quran'),
  ('x80g-9', 'Ethics / Religious Education'),
  ('x80g-9', 'History'),
  ('x80g-9', 'Geography'),
  ('x80g-9', 'Social Studies'),
  ('x80g-9', 'Regional Language'),
  ('x80g-9', 'Arabic'),
  ('x80g-9', 'Persian'),
  ('x80g-9', 'Punjabi'),
  ('x80g-9', 'Sindhi'),
  ('x80g-9', 'Pashto'),
  ('x80g-9', 'Balochi'),
  ('x80g-9', 'Brahui'),
  ('x80g-9', 'English Grammar'),
  ('x80g-9', 'English Literature'),
  ('x80g-9', 'Creative Writing'),
  ('x80g-9', 'Communication Skills'),
  ('x80g-9', 'General Knowledge'),
  ('x80g-9', 'Environmental Studies'),
  ('x80g-9', 'Environmental Education'),
  ('x80g-9', 'Health & Physical Education'),
  ('x80g-9', 'Physical Education'),
  ('x80g-9', 'Art & Drawing'),
  ('x80g-9', 'Fine Arts'),
  ('x80g-9', 'Home Economics'),
  ('x80g-9', 'Agriculture'),
  ('x80g-9', 'Technology'),
  ('x80g-9', 'Information Technology / ICT'),
  ('x80g-9', 'Digital Literacy'),
  ('x80g-9', 'Coding'),
  ('x80g-9', 'Programming'),
  ('x80g-9', 'STEM'),
  ('x80g-9', 'Robotics'),
  ('x80g-9', 'Artificial Intelligence'),
  ('x80g-9', 'Electronics'),
  ('x80g-9', 'Science Projects'),
  ('x80g-9', 'Entrepreneurship'),
  ('x80g-9', 'Financial Literacy'),
  ('x80g-9', 'Life Skills'),
  ('x80g-9', 'Character & Moral Education'),
  ('x80g-9', 'Personal Development'),
  ('x80g-9', 'Drama & Performing Arts'),
  ('x80g-9', 'Music'),
  ('x80g-9', 'Craft'),
  ('x80g-9', 'Library / Reading'),
  ('x80g-9', 'Study Skills'),
  ('x80g-9', 'Public Speaking'),
  ('x80g-9', 'Handwriting'),
  ('x80g-10', 'English'),
  ('x80g-10', 'Urdu'),
  ('x80g-10', 'Mathematics'),
  ('x80g-10', 'General Science'),
  ('x80g-10', 'Computer Science'),
  ('x80g-10', 'Islamiat / Islamic Studies'),
  ('x80g-10', 'Quran Studies / Translation of Holy Quran'),
  ('x80g-10', 'Ethics / Religious Education'),
  ('x80g-10', 'History'),
  ('x80g-10', 'Geography'),
  ('x80g-10', 'Social Studies'),
  ('x80g-10', 'Regional Language'),
  ('x80g-10', 'Arabic'),
  ('x80g-10', 'Persian'),
  ('x80g-10', 'Punjabi'),
  ('x80g-10', 'Sindhi'),
  ('x80g-10', 'Pashto'),
  ('x80g-10', 'Balochi'),
  ('x80g-10', 'Brahui'),
  ('x80g-10', 'English Grammar'),
  ('x80g-10', 'English Literature'),
  ('x80g-10', 'Creative Writing'),
  ('x80g-10', 'Communication Skills'),
  ('x80g-10', 'General Knowledge'),
  ('x80g-10', 'Environmental Studies'),
  ('x80g-10', 'Environmental Education'),
  ('x80g-10', 'Health & Physical Education'),
  ('x80g-10', 'Physical Education'),
  ('x80g-10', 'Art & Drawing'),
  ('x80g-10', 'Fine Arts'),
  ('x80g-10', 'Home Economics'),
  ('x80g-10', 'Agriculture'),
  ('x80g-10', 'Technology'),
  ('x80g-10', 'Information Technology / ICT'),
  ('x80g-10', 'Digital Literacy'),
  ('x80g-10', 'Coding'),
  ('x80g-10', 'Programming'),
  ('x80g-10', 'STEM'),
  ('x80g-10', 'Robotics'),
  ('x80g-10', 'Artificial Intelligence'),
  ('x80g-10', 'Electronics'),
  ('x80g-10', 'Science Projects'),
  ('x80g-10', 'Entrepreneurship'),
  ('x80g-10', 'Financial Literacy'),
  ('x80g-10', 'Life Skills'),
  ('x80g-10', 'Character & Moral Education'),
  ('x80g-10', 'Personal Development'),
  ('x80g-10', 'Drama & Performing Arts'),
  ('x80g-10', 'Music'),
  ('x80g-10', 'Craft'),
  ('x80g-10', 'Library / Reading'),
  ('x80g-10', 'Study Skills'),
  ('x80g-10', 'Public Speaking'),
  ('x80g-10', 'Handwriting'),
  ('x80g-11', 'English'),
  ('x80g-11', 'Urdu'),
  ('x80g-11', 'Mathematics'),
  ('x80g-11', 'General Science'),
  ('x80g-11', 'Computer Science'),
  ('x80g-11', 'Islamiat / Islamic Studies'),
  ('x80g-11', 'Quran Studies / Translation of Holy Quran'),
  ('x80g-11', 'Ethics / Religious Education'),
  ('x80g-11', 'History'),
  ('x80g-11', 'Geography'),
  ('x80g-11', 'Social Studies'),
  ('x80g-11', 'Regional Language'),
  ('x80g-11', 'Arabic'),
  ('x80g-11', 'Persian'),
  ('x80g-11', 'Punjabi'),
  ('x80g-11', 'Sindhi'),
  ('x80g-11', 'Pashto'),
  ('x80g-11', 'Balochi'),
  ('x80g-11', 'Brahui'),
  ('x80g-11', 'English Grammar'),
  ('x80g-11', 'English Literature'),
  ('x80g-11', 'Creative Writing'),
  ('x80g-11', 'Communication Skills'),
  ('x80g-11', 'General Knowledge'),
  ('x80g-11', 'Environmental Studies'),
  ('x80g-11', 'Environmental Education'),
  ('x80g-11', 'Health & Physical Education'),
  ('x80g-11', 'Physical Education'),
  ('x80g-11', 'Art & Drawing'),
  ('x80g-11', 'Fine Arts'),
  ('x80g-11', 'Home Economics'),
  ('x80g-11', 'Agriculture'),
  ('x80g-11', 'Technology'),
  ('x80g-11', 'Information Technology / ICT'),
  ('x80g-11', 'Digital Literacy'),
  ('x80g-11', 'Coding'),
  ('x80g-11', 'Programming'),
  ('x80g-11', 'STEM'),
  ('x80g-11', 'Robotics'),
  ('x80g-11', 'Artificial Intelligence'),
  ('x80g-11', 'Electronics'),
  ('x80g-11', 'Science Projects'),
  ('x80g-11', 'Entrepreneurship'),
  ('x80g-11', 'Financial Literacy'),
  ('x80g-11', 'Life Skills'),
  ('x80g-11', 'Character & Moral Education'),
  ('x80g-11', 'Personal Development'),
  ('x80g-11', 'Drama & Performing Arts'),
  ('x80g-11', 'Music'),
  ('x80g-11', 'Craft'),
  ('x80g-11', 'Library / Reading'),
  ('x80g-11', 'Study Skills'),
  ('x80g-11', 'Public Speaking'),
  ('x80g-11', 'Handwriting'),
  ('x80g-12', 'English'),
  ('x80g-12', 'Urdu'),
  ('x80g-12', 'Mathematics'),
  ('x80g-12', 'Islamiyat / Islamic Studies'),
  ('x80g-12', 'Pakistan Studies'),
  ('x80g-12', 'General Science'),
  ('x80g-12', 'Economics'),
  ('x80g-12', 'Civics'),
  ('x80g-12', 'Education'),
  ('x80g-12', 'History'),
  ('x80g-12', 'Geography'),
  ('x80g-12', 'Arabic'),
  ('x80g-12', 'Persian'),
  ('x80g-12', 'Punjabi'),
  ('x80g-12', 'Home Economics'),
  ('x80g-12', 'Fine Arts'),
  ('x80g-12', 'Drawing'),
  ('x80g-12', 'Computer Science'),
  ('x80g-12', 'Information Technology'),
  ('x80g-12', 'Physical Education'),
  ('x80g-12', 'Health & Physical Education'),
  ('x80g-12', 'Punjabi Elective'),
  ('x80g-12', 'Arabic Elective'),
  ('x80g-12', 'Persian Elective'),
  ('x80g-12', 'Civics Elective'),
  ('x80g-12', 'Economics Elective'),
  ('x80g-12', 'Education Elective'),
  ('x80g-12', 'History Elective'),
  ('x80g-12', 'Geography Elective'),
  ('x80g-12', 'Home Economics Elective'),
  ('x80g-12', 'Fine Arts Elective'),
  ('x80g-12', 'Computer Science Elective'),
  ('x80g-12', 'Islamic Studies Elective'),
  ('x80g-12', 'Additional Mathematics'),
  ('x80g-13', 'English'),
  ('x80g-13', 'Urdu'),
  ('x80g-13', 'Mathematics'),
  ('x80g-13', 'Islamiyat / Islamic Studies'),
  ('x80g-13', 'Pakistan Studies'),
  ('x80g-13', 'General Science'),
  ('x80g-13', 'Economics'),
  ('x80g-13', 'Civics'),
  ('x80g-13', 'Education'),
  ('x80g-13', 'History'),
  ('x80g-13', 'Geography'),
  ('x80g-13', 'Arabic'),
  ('x80g-13', 'Persian'),
  ('x80g-13', 'Punjabi'),
  ('x80g-13', 'Home Economics'),
  ('x80g-13', 'Fine Arts'),
  ('x80g-13', 'Drawing'),
  ('x80g-13', 'Computer Science'),
  ('x80g-13', 'Information Technology'),
  ('x80g-13', 'Physical Education'),
  ('x80g-13', 'Health & Physical Education'),
  ('x80g-13', 'Punjabi Elective'),
  ('x80g-13', 'Arabic Elective'),
  ('x80g-13', 'Persian Elective'),
  ('x80g-13', 'Civics Elective'),
  ('x80g-13', 'Economics Elective'),
  ('x80g-13', 'Education Elective'),
  ('x80g-13', 'History Elective'),
  ('x80g-13', 'Geography Elective'),
  ('x80g-13', 'Home Economics Elective'),
  ('x80g-13', 'Fine Arts Elective'),
  ('x80g-13', 'Computer Science Elective'),
  ('x80g-13', 'Islamic Studies Elective'),
  ('x80g-13', 'Additional Mathematics'),
  ('x80g-14', 'English'),
  ('x80g-14', 'Urdu'),
  ('x80g-14', 'Mathematics'),
  ('x80g-14', 'Physics'),
  ('x80g-14', 'Chemistry'),
  ('x80g-14', 'Biology'),
  ('x80g-14', 'Computer Science'),
  ('x80g-14', 'Islamiyat / Islamic Studies'),
  ('x80g-14', 'Pakistan Studies'),
  ('x80g-14', 'General Science'),
  ('x80g-14', 'Translation of the Holy Quran'),
  ('x80g-14', 'Nazra Quran'),
  ('x80g-14', 'Quran Studies'),
  ('x80g-14', 'Arabic'),
  ('x80g-14', 'Punjabi'),
  ('x80g-14', 'Sindhi'),
  ('x80g-14', 'Pashto'),
  ('x80g-14', 'Balochi'),
  ('x80g-14', 'Ethics'),
  ('x80g-14', 'Religious Education'),
  ('x80g-14', 'Information Technology'),
  ('x80g-14', 'ICT'),
  ('x80g-14', 'Additional Mathematics'),
  ('x80g-14', 'General Mathematics'),
  ('x80g-15', 'English'),
  ('x80g-15', 'Urdu'),
  ('x80g-15', 'Mathematics'),
  ('x80g-15', 'Physics'),
  ('x80g-15', 'Chemistry'),
  ('x80g-15', 'Biology'),
  ('x80g-15', 'Computer Science'),
  ('x80g-15', 'Islamiyat / Islamic Studies'),
  ('x80g-15', 'Pakistan Studies'),
  ('x80g-15', 'General Science'),
  ('x80g-15', 'Translation of the Holy Quran'),
  ('x80g-15', 'Nazra Quran'),
  ('x80g-15', 'Quran Studies'),
  ('x80g-15', 'Arabic'),
  ('x80g-15', 'Punjabi'),
  ('x80g-15', 'Sindhi'),
  ('x80g-15', 'Pashto'),
  ('x80g-15', 'Balochi'),
  ('x80g-15', 'Ethics'),
  ('x80g-15', 'Religious Education'),
  ('x80g-15', 'Information Technology'),
  ('x80g-15', 'ICT'),
  ('x80g-15', 'Additional Mathematics'),
  ('x80g-15', 'General Mathematics'),
  ('x80g-16', 'English'),
  ('x80g-16', 'Mathematics'),
  ('x80g-16', 'Biology'),
  ('x80g-16', 'Chemistry'),
  ('x80g-16', 'Physics'),
  ('x80g-16', 'Combined Science'),
  ('x80g-16', 'Co-ordinated Sciences'),
  ('x80g-16', 'Computer Science'),
  ('x80g-16', 'ICT'),
  ('x80g-16', 'Pakistan Studies'),
  ('x80g-16', 'Islamiyat'),
  ('x80g-16', 'Urdu'),
  ('x80g-16', 'Accounting'),
  ('x80g-16', 'Business Studies'),
  ('x80g-16', 'Economics'),
  ('x80g-16', 'Geography'),
  ('x80g-16', 'History'),
  ('x80g-16', 'Sociology'),
  ('x80g-16', 'Environmental Management'),
  ('x80g-16', 'Art & Design'),
  ('x80g-16', 'Design & Technology'),
  ('x80g-16', 'Physical Education'),
  ('x80g-16', 'Literature in English'),
  ('x80g-16', 'Global Perspectives'),
  ('x80g-16', 'Arabic'),
  ('x80g-17', 'English Language'),
  ('x80g-17', 'Literature in English'),
  ('x80g-17', 'Mathematics'),
  ('x80g-17', 'Additional Mathematics'),
  ('x80g-17', 'Biology'),
  ('x80g-17', 'Chemistry'),
  ('x80g-17', 'Physics'),
  ('x80g-17', 'Combined Science'),
  ('x80g-17', 'Environmental Management'),
  ('x80g-17', 'Accounting'),
  ('x80g-17', 'Business Studies'),
  ('x80g-17', 'Economics'),
  ('x80g-17', 'Commerce'),
  ('x80g-17', 'Computer Science'),
  ('x80g-17', 'Statistics'),
  ('x80g-17', 'Geography'),
  ('x80g-17', 'History'),
  ('x80g-17', 'Sociology'),
  ('x80g-17', 'Global Perspectives'),
  ('x80g-17', 'Pakistan Studies'),
  ('x80g-17', 'Islamiyat'),
  ('x80g-17', 'Islamic Studies'),
  ('x80g-17', 'Arabic'),
  ('x80g-17', 'Urdu as a First Language'),
  ('x80g-17', 'Urdu as a Second Language'),
  ('x80g-17', 'Art & Design'),
  ('x80g-17', 'Food & Nutrition'),
  ('x80g-17', 'Fashion & Textiles'),
  ('x80g-17', 'Travel & Tourism'),
  ('x80g-17', 'Physical Education'),
  ('x80g-17', 'Agriculture'),
  ('x80g-17', 'Bangladesh Studies'),
  ('x80g-17', 'Bengali'),
  ('x80g-17', 'Sinhala'),
  ('x80g-17', 'Tamil'),
  ('x80g-17', 'Biblical Studies'),
  ('x80g-18', 'Accounting'),
  ('x80g-18', 'Arabic'),
  ('x80g-18', 'Art & Design'),
  ('x80g-18', 'Biblical Studies'),
  ('x80g-18', 'Biology'),
  ('x80g-18', 'Business'),
  ('x80g-18', 'Chemistry'),
  ('x80g-18', 'Chinese Language'),
  ('x80g-18', 'Chinese Language & Literature'),
  ('x80g-18', 'Classical Studies'),
  ('x80g-18', 'Computer Science'),
  ('x80g-18', 'Design & Technology'),
  ('x80g-18', 'Digital Media & Design'),
  ('x80g-18', 'Drama'),
  ('x80g-18', 'Economics'),
  ('x80g-18', 'English Language'),
  ('x80g-18', 'English Language & Literature'),
  ('x80g-18', 'English Literature'),
  ('x80g-18', 'English General Paper'),
  ('x80g-18', 'Environmental Management'),
  ('x80g-18', 'European History'),
  ('x80g-18', 'French Language'),
  ('x80g-18', 'French Language & Literature'),
  ('x80g-18', 'Geography'),
  ('x80g-18', 'German Language'),
  ('x80g-18', 'German Language & Literature'),
  ('x80g-18', 'Global Perspectives & Research'),
  ('x80g-18', 'History'),
  ('x80g-18', 'Hinduism'),
  ('x80g-18', 'Information Technology'),
  ('x80g-18', 'International History'),
  ('x80g-18', 'Islamic Studies'),
  ('x80g-18', 'Law'),
  ('x80g-18', 'Marine Science'),
  ('x80g-18', 'Mathematics'),
  ('x80g-18', 'Further Mathematics'),
  ('x80g-18', 'Media Studies'),
  ('x80g-18', 'Music'),
  ('x80g-18', 'Physics'),
  ('x80g-18', 'Portuguese'),
  ('x80g-18', 'Psychology'),
  ('x80g-18', 'Sociology'),
  ('x80g-18', 'Spanish Language'),
  ('x80g-18', 'Spanish Language & Literature'),
  ('x80g-18', 'Sport & Physical Education'),
  ('x80g-18', 'Tamil'),
  ('x80g-18', 'Thinking Skills'),
  ('x80g-18', 'Travel & Tourism'),
  ('x80g-18', 'Urdu'),
  ('x80g-18', 'Urdu Language & Literature'),
  ('x80g-18', 'Urdu – Pakistan'),
  ('x80g-18', 'US History'),
  ('x80g-18', 'Statistics'),
  ('x80g-18', 'Environmental Science'),
  ('x80g-18', 'Economics & Business'),
  ('x80g-18', 'Pakistan Studies'),
  ('x80g-18', 'Religious Studies'),
  ('x80g-19', 'English'),
  ('x80g-19', 'Urdu'),
  ('x80g-19', 'Islamic Education / Islamiat'),
  ('x80g-19', 'Pakistan Studies'),
  ('x80g-19', 'Translation of the Holy Quran'),
  ('x80g-19', 'Ethics / Religious Education'),
  ('x80g-19', 'History'),
  ('x80g-19', 'History of Islam'),
  ('x80g-19', 'History of Muslim India'),
  ('x80g-19', 'History of Pakistan'),
  ('x80g-19', 'History of the Modern World'),
  ('x80g-19', 'Economics'),
  ('x80g-19', 'Geography'),
  ('x80g-19', 'Civics'),
  ('x80g-19', 'Philosophy'),
  ('x80g-19', 'Psychology'),
  ('x80g-19', 'Sociology'),
  ('x80g-19', 'Statistics'),
  ('x80g-19', 'Islamic Studies'),
  ('x80g-19', 'Education'),
  ('x80g-19', 'Home Economics'),
  ('x80g-19', 'Outlines of Home Economics'),
  ('x80g-19', 'Fine Arts'),
  ('x80g-19', 'Music'),
  ('x80g-19', 'Arabic'),
  ('x80g-19', 'Persian'),
  ('x80g-19', 'Punjabi'),
  ('x80g-19', 'Sindhi'),
  ('x80g-19', 'Pashto'),
  ('x80g-19', 'Saraiki'),
  ('x80g-19', 'Urdu Advance'),
  ('x80g-19', 'English Elective'),
  ('x80g-19', 'French'),
  ('x80g-19', 'German'),
  ('x80g-19', 'Health & Physical Education'),
  ('x80g-19', 'Military Science'),
  ('x80g-19', 'Geology'),
  ('x80g-19', 'Library Science'),
  ('x80g-19', 'Computer Science'),
  ('x80g-19', 'Computer Science & Entrepreneurship'),
  ('x80g-19', 'Mathematics'),
  ('x80g-19', 'Agriculture'),
  ('x80g-19', 'Nursing'),
  ('x80g-19', 'Commercial Practices'),
  ('x80g-19', 'Applied Art'),
  ('x80g-19', 'Food & Nutrition'),
  ('x80g-19', 'Child Development & Family Living'),
  ('x80g-19', 'Clothing & Textile'),
  ('x80g-19', 'Entrepreneurship'),
  ('x80g-19', 'General Science'),
  ('x80g-19', 'Information Technology / ICT'),
  ('x80g-19', 'Media Studies'),
  ('x80g-19', 'Environmental Studies'),
  ('x80g-20', 'English'),
  ('x80g-20', 'Urdu'),
  ('x80g-20', 'Islamiyat / Islamic Studies'),
  ('x80g-20', 'Pakistan Studies'),
  ('x80g-20', 'Translation of the Holy Quran'),
  ('x80g-20', 'Ethics / Religious Education'),
  ('x80g-20', 'Physics'),
  ('x80g-20', 'Chemistry'),
  ('x80g-20', 'Biology'),
  ('x80g-20', 'Mathematics'),
  ('x80g-20', 'Statistics'),
  ('x80g-20', 'Economics'),
  ('x80g-20', 'Computer Science'),
  ('x80g-20', 'Computer Science & Entrepreneurship'),
  ('x80g-20', 'General Science'),
  ('x80g-20', 'Information Technology / ICT'),
  ('x80g-20', 'Environmental Science'),
  ('x80g-20', 'Geology'),
  ('x80g-20', 'Agriculture'),
  ('x80g-20', 'Health & Physical Education'),
  ('x80g-20', 'Physical Education'),
  ('x80g-20', 'Library Science'),
  ('x80g-21', 'English'),
  ('x80g-21', 'Urdu'),
  ('x80g-21', 'Pakistan Studies'),
  ('x80g-21', 'Islamiyat / Islamic Studies'),
  ('x80g-21', 'Translation of the Holy Quran'),
  ('x80g-21', 'Ethics / Religious Education'),
  ('x80g-21', 'Mathematics'),
  ('x80g-21', 'Statistics'),
  ('x80g-21', 'Computer Science'),
  ('x80g-21', 'Information Technology / ICT'),
  ('x80g-21', 'Physics'),
  ('x80g-21', 'Chemistry'),
  ('x80g-21', 'Biology'),
  ('x80g-21', 'Economics'),
  ('x80g-21', 'Accounting'),
  ('x80g-21', 'Finance'),
  ('x80g-21', 'Business Studies'),
  ('x80g-21', 'Management'),
  ('x80g-21', 'Marketing'),
  ('x80g-21', 'Human Resource Management'),
  ('x80g-21', 'Entrepreneurship'),
  ('x80g-21', 'Commerce'),
  ('x80g-21', 'Education'),
  ('x80g-21', 'Psychology'),
  ('x80g-21', 'Sociology'),
  ('x80g-21', 'Political Science'),
  ('x80g-21', 'International Relations'),
  ('x80g-21', 'History'),
  ('x80g-21', 'Geography'),
  ('x80g-21', 'English Literature'),
  ('x80g-21', 'English Language & Linguistics'),
  ('x80g-21', 'Arabic'),
  ('x80g-21', 'Punjabi'),
  ('x80g-21', 'Islamic Studies'),
  ('x80g-21', 'Mass Communication'),
  ('x80g-21', 'Journalism'),
  ('x80g-21', 'Library & Information Science'),
  ('x80g-21', 'Social Work'),
  ('x80g-21', 'Public Administration'),
  ('x80g-21', 'Environmental Science'),
  ('x80g-21', 'Physical Education'),
  ('x80g-21', 'Fine Arts'),
  ('x80g-21', 'Home Economics'),
  ('x80g-21', 'Agriculture'),
  ('x80g-21', 'Food Science & Technology'),
  ('x80g-21', 'Botany'),
  ('x80g-21', 'Zoology'),
  ('x80g-21', 'Microbiology'),
  ('x80g-21', 'Biotechnology'),
  ('x80g-21', 'Geology'),
  ('x80g-21', 'Computer Programming'),
  ('x80g-21', 'Database Management'),
  ('x80g-21', 'Web Development'),
  ('x80g-21', 'Graphic Design'),
  ('x80g-21', 'Digital Marketing'),
  ('x80g-21', 'Data Science'),
  ('x80g-21', 'Artificial Intelligence'),
  ('x80g-21', 'Cyber Security'),
  ('x80g-21', 'Business Analytics'),
  ('x80g-21', 'Supply Chain Management'),
  ('x80g-21', 'Project Management'),
  ('x80g-21', 'Banking & Finance'),
  ('x80g-21', 'Islamic Banking & Finance'),
  ('x80g-21', 'Tourism & Hospitality Management'),
  ('x80g-21', 'Special Education'),
  ('x80g-21', 'Early Childhood Education'),
  ('x80g-21', 'Public Health'),
  ('x80g-21', 'Human Nutrition & Dietetics'),
  ('x80g-22', 'English'),
  ('x80g-22', 'Urdu'),
  ('x80g-22', 'Pakistan Studies'),
  ('x80g-22', 'Islamiyat / Islamic Studies'),
  ('x80g-22', 'Translation of the Holy Quran'),
  ('x80g-22', 'Ethics / Religious Education'),
  ('x80g-22', 'Mathematics'),
  ('x80g-22', 'Statistics'),
  ('x80g-22', 'Computer Science'),
  ('x80g-22', 'Information Technology'),
  ('x80g-22', 'Artificial Intelligence'),
  ('x80g-22', 'Data Science'),
  ('x80g-22', 'Cyber Security'),
  ('x80g-22', 'Software Engineering'),
  ('x80g-22', 'Information Systems'),
  ('x80g-22', 'Computer Engineering'),
  ('x80g-22', 'Electrical Engineering'),
  ('x80g-22', 'Electronics Engineering'),
  ('x80g-22', 'Mechanical Engineering'),
  ('x80g-22', 'Civil Engineering'),
  ('x80g-22', 'Chemical Engineering'),
  ('x80g-22', 'Biomedical Engineering'),
  ('x80g-22', 'Environmental Engineering'),
  ('x80g-22', 'Architecture'),
  ('x80g-22', 'Accounting'),
  ('x80g-22', 'Finance'),
  ('x80g-22', 'Banking & Finance'),
  ('x80g-22', 'Business Administration'),
  ('x80g-22', 'Business Analytics'),
  ('x80g-22', 'Marketing'),
  ('x80g-22', 'Human Resource Management'),
  ('x80g-22', 'Entrepreneurship'),
  ('x80g-22', 'Supply Chain Management'),
  ('x80g-22', 'Project Management'),
  ('x80g-22', 'Economics'),
  ('x80g-22', 'Commerce'),
  ('x80g-22', 'Education'),
  ('x80g-22', 'Early Childhood Education'),
  ('x80g-22', 'Elementary Education'),
  ('x80g-22', 'Secondary Education'),
  ('x80g-22', 'Special Education'),
  ('x80g-22', 'Educational Leadership & Management'),
  ('x80g-22', 'Psychology'),
  ('x80g-22', 'Applied Psychology'),
  ('x80g-22', 'Sociology'),
  ('x80g-22', 'Social Work'),
  ('x80g-22', 'Political Science'),
  ('x80g-22', 'International Relations'),
  ('x80g-22', 'Public Administration'),
  ('x80g-22', 'Law'),
  ('x80g-22', 'History'),
  ('x80g-22', 'Geography'),
  ('x80g-22', 'Islamic Studies'),
  ('x80g-22', 'English Literature'),
  ('x80g-22', 'English Language & Linguistics'),
  ('x80g-22', 'Urdu Literature'),
  ('x80g-22', 'Arabic'),
  ('x80g-22', 'Punjabi'),
  ('x80g-22', 'Persian'),
  ('x80g-22', 'Mass Communication'),
  ('x80g-22', 'Journalism'),
  ('x80g-22', 'Media Studies'),
  ('x80g-22', 'Development Studies'),
  ('x80g-22', 'Peace & Conflict Studies'),
  ('x80g-22', 'Environmental Science'),
  ('x80g-22', 'Environmental Studies'),
  ('x80g-22', 'Biology'),
  ('x80g-22', 'Botany'),
  ('x80g-22', 'Zoology'),
  ('x80g-22', 'Microbiology'),
  ('x80g-22', 'Biotechnology'),
  ('x80g-22', 'Biochemistry'),
  ('x80g-22', 'Chemistry'),
  ('x80g-22', 'Physics'),
  ('x80g-22', 'Applied Mathematics'),
  ('x80g-22', 'Geology'),
  ('x80g-22', 'Agriculture'),
  ('x80g-22', 'Agronomy'),
  ('x80g-22', 'Horticulture'),
  ('x80g-22', 'Food Science & Technology'),
  ('x80g-22', 'Food & Nutrition'),
  ('x80g-22', 'Human Nutrition & Dietetics'),
  ('x80g-22', 'Public Health'),
  ('x80g-22', 'Pharmacy'),
  ('x80g-22', 'Nursing'),
  ('x80g-22', 'Allied Health Sciences'),
  ('x80g-22', 'Medical Laboratory Technology'),
  ('x80g-22', 'Physiotherapy'),
  ('x80g-22', 'Physical Education'),
  ('x80g-22', 'Sports Sciences'),
  ('x80g-22', 'Fine Arts'),
  ('x80g-22', 'Visual Arts'),
  ('x80g-22', 'Graphic Design'),
  ('x80g-22', 'Fashion Design'),
  ('x80g-22', 'Textile Design'),
  ('x80g-22', 'Interior Design'),
  ('x80g-22', 'Design & Technology'),
  ('x80g-22', 'Tourism & Hospitality Management'),
  ('x80g-22', 'Hotel Management'),
  ('x80g-22', 'Aviation Management'),
  ('x80g-22', 'Library & Information Science'),
  ('x80g-22', 'Environmental Management'),
  ('x80g-22', 'Media & Communication'),
  ('x80g-22', 'Film & Television'),
  ('x80g-22', 'Theatre & Performing Arts'),
  ('x80g-22', 'Music'),
  ('x80g-22', 'Islamic Banking & Finance'),
  ('x80g-22', 'Islamic Economics'),
  ('x80g-22', 'Actuarial Science'),
  ('x80g-22', 'Operations Research'),
  ('x80g-22', 'Artificial Intelligence & Robotics'),
  ('x80g-22', 'Blockchain Technology'),
  ('x80g-22', 'Cloud Computing'),
  ('x80g-22', 'Web Development'),
  ('x80g-22', 'Mobile Application Development'),
  ('x80g-22', 'Game Development'),
  ('x80g-22', 'Digital Marketing'),
  ('x80g-22', 'E-Commerce'),
  ('x80g-22', 'FinTech'),
  ('x80g-22', 'Renewable Energy'),
  ('x80g-22', 'Energy Engineering'),
  ('x80g-22', 'Telecommunication Engineering'),
  ('x80g-22', 'Mechatronics Engineering'),
  ('x80g-22', 'Robotics Engineering'),
  ('x80g-23', 'GRE Preparation'),
  ('x80g-23', 'GMAT Preparation'),
  ('x80g-23', 'IELTS Preparation'),
  ('x80g-23', 'TOEFL Preparation'),
  ('x80g-23', 'PTE Academic Preparation'),
  ('x80g-23', 'MDCAT Preparation'),
  ('x80g-23', 'ECAT Preparation'),
  ('x80g-23', 'NET Preparation'),
  ('x80g-23', 'FAST-NU Admission Test Preparation'),
  ('x80g-23', 'GIKI Admission Test Preparation'),
  ('x80g-23', 'COMSATS Admission Test Preparation'),
  ('x80g-23', 'LUMS Admission Test Preparation'),
  ('x80g-23', 'NTS Test Preparation'),
  ('x80g-23', 'NAT Preparation'),
  ('x80g-23', 'GAT General Preparation'),
  ('x80g-23', 'GAT Subject Preparation'),
  ('x80g-23', 'ETEA Test Preparation'),
  ('x80g-23', 'ECAT Engineering Entry Test Preparation'),
  ('x80g-23', 'University Admission Test Preparation'),
  ('x80g-23', 'Medical Entry Test Preparation'),
  ('x80g-23', 'Engineering Entry Test Preparation'),
  ('x80g-23', 'Law Admission Test (LAT) Preparation'),
  ('x80g-23', 'Law GAT Preparation'),
  ('x80g-23', 'CSS Preparation'),
  ('x80g-23', 'PMS Preparation'),
  ('x80g-23', 'FPSC Test Preparation'),
  ('x80g-23', 'PPSC Test Preparation'),
  ('x80g-23', 'SPSC Test Preparation'),
  ('x80g-23', 'KPPSC Test Preparation'),
  ('x80g-23', 'BPSC Test Preparation'),
  ('x80g-23', 'AJKPSC Test Preparation'),
  ('x80g-23', 'NTS Recruitment Test Preparation'),
  ('x80g-23', 'FPSC Competitive Exam Preparation'),
  ('x80g-23', 'Police Recruitment Test Preparation'),
  ('x80g-23', 'Armed Forces Test Preparation'),
  ('x80g-23', 'ISSB Preparation'),
  ('x80g-23', 'Pakistan Army Initial Test Preparation'),
  ('x80g-23', 'Pakistan Navy Test Preparation'),
  ('x80g-23', 'Pakistan Air Force Test Preparation'),
  ('x80g-23', 'Cadet College Entry Test Preparation'),
  ('x80g-23', 'Military College Entry Test Preparation'),
  ('x80g-23', 'Scholarship Test Preparation'),
  ('x80g-23', 'School Admission Test Preparation'),
  ('x80g-23', 'College Admission Test Preparation'),
  ('x80g-23', 'University Entrance Test Preparation'),
  ('x80g-23', 'English Proficiency Test Preparation'),
  ('x80g-23', 'General Aptitude Test Preparation'),
  ('x80g-23', 'Verbal Reasoning'),
  ('x80g-23', 'Quantitative Reasoning'),
  ('x80g-23', 'Logical Reasoning'),
  ('x80g-23', 'Analytical Reasoning'),
  ('x80g-23', 'Non-Verbal Reasoning'),
  ('x80g-23', 'IQ Test Preparation'),
  ('x80g-23', 'General Knowledge Test Preparation'),
  ('x80g-23', 'Current Affairs Test Preparation'),
  ('x80g-23', 'Subject Specialist Test Preparation'),
  ('x80g-23', 'Teaching Recruitment Test Preparation'),
  ('x80g-23', 'Educator Test Preparation'),
  ('x80g-23', 'Banking Test Preparation'),
  ('x80g-23', 'Accounting & Finance Test Preparation'),
  ('x80g-23', 'Computer-Based Test Preparation'),
  ('x80g-23', 'Typing Test Preparation'),
  ('x80g-23', 'Driving License Test Preparation'),
  ('x80g-23', 'Vocational Test Preparation'),
  ('x80g-24', 'English'),
  ('x80g-24', 'English Literature'),
  ('x80g-24', 'English Language & Linguistics'),
  ('x80g-24', 'Urdu'),
  ('x80g-24', 'Punjabi'),
  ('x80g-24', 'Arabic'),
  ('x80g-24', 'Persian'),
  ('x80g-24', 'Islamic Studies'),
  ('x80g-24', 'Quranic Studies'),
  ('x80g-24', 'Hadith Studies'),
  ('x80g-24', 'Comparative Religion'),
  ('x80g-24', 'Education'),
  ('x80g-24', 'Educational Leadership & Management'),
  ('x80g-24', 'Teacher Education'),
  ('x80g-24', 'Early Childhood Education'),
  ('x80g-24', 'Special Education'),
  ('x80g-24', 'Educational Psychology'),
  ('x80g-24', 'Curriculum & Instruction'),
  ('x80g-24', 'Educational Technology'),
  ('x80g-24', 'Educational Planning & Management'),
  ('x80g-24', 'Psychology'),
  ('x80g-24', 'Clinical Psychology'),
  ('x80g-24', 'Applied Psychology'),
  ('x80g-24', 'Sociology'),
  ('x80g-24', 'Social Work'),
  ('x80g-24', 'Political Science'),
  ('x80g-24', 'International Relations'),
  ('x80g-24', 'Public Administration'),
  ('x80g-24', 'History'),
  ('x80g-24', 'Geography'),
  ('x80g-24', 'Pakistan Studies'),
  ('x80g-24', 'Economics'),
  ('x80g-24', 'Commerce'),
  ('x80g-24', 'Business Administration'),
  ('x80g-24', 'Management Sciences'),
  ('x80g-24', 'Marketing'),
  ('x80g-24', 'Finance'),
  ('x80g-24', 'Accounting'),
  ('x80g-24', 'Human Resource Management'),
  ('x80g-24', 'Entrepreneurship'),
  ('x80g-24', 'Supply Chain Management'),
  ('x80g-24', 'Business Analytics'),
  ('x80g-24', 'Computer Science'),
  ('x80g-24', 'Information Technology'),
  ('x80g-24', 'Software Engineering'),
  ('x80g-24', 'Artificial Intelligence'),
  ('x80g-24', 'Data Science'),
  ('x80g-24', 'Cyber Security'),
  ('x80g-24', 'Information Systems'),
  ('x80g-24', 'Mathematics'),
  ('x80g-24', 'Applied Mathematics'),
  ('x80g-24', 'Statistics'),
  ('x80g-24', 'Physics'),
  ('x80g-24', 'Chemistry'),
  ('x80g-24', 'Biochemistry'),
  ('x80g-24', 'Biology'),
  ('x80g-24', 'Botany'),
  ('x80g-24', 'Zoology'),
  ('x80g-24', 'Microbiology'),
  ('x80g-24', 'Biotechnology'),
  ('x80g-24', 'Environmental Science'),
  ('x80g-24', 'Environmental Management'),
  ('x80g-24', 'Geology'),
  ('x80g-24', 'Food Science & Technology'),
  ('x80g-24', 'Food & Nutrition'),
  ('x80g-24', 'Human Nutrition & Dietetics'),
  ('x80g-24', 'Agriculture'),
  ('x80g-24', 'Agronomy'),
  ('x80g-24', 'Horticulture'),
  ('x80g-24', 'Plant Sciences'),
  ('x80g-24', 'Animal Sciences'),
  ('x80g-24', 'Veterinary Sciences'),
  ('x80g-24', 'Public Health'),
  ('x80g-24', 'Epidemiology'),
  ('x80g-24', 'Pharmacy'),
  ('x80g-24', 'Pharmaceutical Sciences'),
  ('x80g-24', 'Pharmacology'),
  ('x80g-24', 'Medical Laboratory Sciences'),
  ('x80g-24', 'Physiotherapy'),
  ('x80g-24', 'Physical Education'),
  ('x80g-24', 'Sports Sciences'),
  ('x80g-24', 'Fine Arts'),
  ('x80g-24', 'Visual Arts'),
  ('x80g-24', 'Art & Design'),
  ('x80g-24', 'Graphic Design'),
  ('x80g-24', 'Media Studies'),
  ('x80g-24', 'Mass Communication'),
  ('x80g-24', 'Journalism'),
  ('x80g-24', 'Film & Television'),
  ('x80g-24', 'Library & Information Science'),
  ('x80g-24', 'Development Studies'),
  ('x80g-24', 'Peace & Conflict Studies'),
  ('x80g-24', 'Gender Studies'),
  ('x80g-24', 'International Development'),
  ('x80g-24', 'Defence & Strategic Studies'),
  ('x80g-24', 'Defence Studies'),
  ('x80g-24', 'Law'),
  ('x80g-24', 'Criminology'),
  ('x80g-24', 'Anthropology'),
  ('x80g-24', 'Archaeology'),
  ('x80g-24', 'Philosophy'),
  ('x80g-24', 'Economics & Finance'),
  ('x80g-24', 'Islamic Economics'),
  ('x80g-24', 'Islamic Banking & Finance'),
  ('x80g-24', 'Islamic Finance'),
  ('x80g-24', 'Actuarial Science'),
  ('x80g-24', 'Data Analytics'),
  ('x80g-24', 'Artificial Intelligence & Robotics'),
  ('x80g-24', 'Renewable Energy'),
  ('x80g-24', 'Energy Studies'),
  ('x80g-24', 'Climate Change'),
  ('x80g-24', 'Biotechnology & Genetic Engineering'),
  ('x80g-24', 'Molecular Biology'),
  ('x80g-24', 'Genetics'),
  ('x80g-24', 'Bioinformatics'),
  ('x80g-24', 'Neuroscience'),
  ('x80g-24', 'Nanotechnology'),
  ('x80g-24', 'Materials Science'),
  ('x80g-24', 'Computational Physics'),
  ('x80g-24', 'Computational Mathematics'),
  ('x80g-24', 'Computational Biology'),
  ('x80g-24', 'Remote Sensing & GIS'),
  ('x80g-24', 'Tourism & Hospitality Management'),
  ('x80g-24', 'International Business'),
  ('x80g-24', 'Project Management'),
  ('x80g-24', 'Operations Management'),
  ('x80g-24', 'Organizational Psychology'),
  ('x80g-24', 'Organizational Behavior'),
  ('x80g-24', 'Leadership & Management'),
  ('x80g-25', 'Nazra Quran'),
  ('x80g-25', 'Hifzul Quran'),
  ('x80g-25', 'Translation of Quran'),
  ('x80g-26', 'Chess'),
  ('x80g-26', 'Ludo'),
  ('x80g-26', 'Carrom'),
  ('x80g-26', 'Scrabble'),
  ('x80g-26', 'Rubik''s Cube'),
  ('x80g-26', 'Darts'),
  ('x80g-26', 'Table Tennis'),
  ('x80g-26', 'Badminton'),
  ('x80g-26', 'Basketball Skills'),
  ('x80g-26', 'Football Skills'),
  ('x80g-26', 'Cricket Skills'),
  ('x80g-26', 'Tennis Skills'),
  ('x80g-26', 'Hockey Skills'),
  ('x80g-26', 'Futsal Skills'),
  ('x80g-26', 'Volleyball Skills'),
  ('x80g-26', 'Athletics'),
  ('x80g-26', 'Running'),
  ('x80g-26', 'Fitness Training'),
  ('x80g-26', 'Physical Fitness'),
  ('x80g-26', 'Yoga'),
  ('x80g-26', 'Gymnastics'),
  ('x80g-26', 'Skipping'),
  ('x80g-26', 'Cycling'),
  ('x80g-26', 'Roller Skating'),
  ('x80g-26', 'Skating'),
  ('x80g-26', 'Karate'),
  ('x80g-26', 'Taekwondo'),
  ('x80g-26', 'Judo'),
  ('x80g-26', 'Martial Arts'),
  ('x80g-26', 'Self-Defense'),
  ('x80g-26', 'Boxing Fitness'),
  ('x80g-26', 'Wrestling'),
  ('x80g-26', 'Archery'),
  ('x80g-26', 'Dance'),
  ('x80g-26', 'Ballet'),
  ('x80g-26', 'Swimming Theory & Dry Training'),
  ('x80g-26', 'Sports Skills Development'),
  ('x80g-26', 'Motor Skills Development'),
  ('x80g-26', 'Coordination Training'),
  ('x80g-26', 'Balance Training'),
  ('x80g-26', 'Agility Training'),
  ('x80g-26', 'Speed & Reaction Training'),
  ('x80g-26', 'Strength & Conditioning'),
  ('x80g-26', 'Endurance Training'),
  ('x80g-26', 'Sports Fitness'),
  ('x80g-26', 'Sports Psychology'),
  ('x80g-26', 'Sports Strategy & Tactics'),
  ('x80g-26', 'Referee & Rules Training'),
  ('x80g-26', 'E-Sports'),
  ('x80g-26', 'Gaming Skills'),
  ('x80g-26', 'Mind Games'),
  ('x80g-26', 'Board Games'),
  ('x80g-27', 'Language'),
  ('x80g-27', 'Social Studies'),
  ('x80g-27', 'Mathematics'),
  ('x80g-27', 'Science'),
  ('x80g-27', 'Arts'),
  ('x80g-27', 'Personal, Social & Physical Education'),
  ('x80g-27', 'Language & Literature'),
  ('x80g-27', 'Language Acquisition'),
  ('x80g-27', 'Individuals & Societies'),
  ('x80g-27', 'Sciences'),
  ('x80g-27', 'Physical & Health Education'),
  ('x80g-27', 'Design'),
  ('x80g-27', 'Language A: Literature'),
  ('x80g-27', 'Language A: Language & Literature'),
  ('x80g-27', 'Literature & Performance'),
  ('x80g-27', 'Language B'),
  ('x80g-27', 'Language ab initio'),
  ('x80g-27', 'Classical Languages'),
  ('x80g-27', 'Business Management'),
  ('x80g-27', 'Digital Society'),
  ('x80g-27', 'Economics'),
  ('x80g-27', 'Geography'),
  ('x80g-27', 'Global Politics'),
  ('x80g-27', 'History'),
  ('x80g-27', 'Philosophy'),
  ('x80g-27', 'Psychology'),
  ('x80g-27', 'Social & Cultural Anthropology'),
  ('x80g-27', 'World Religions'),
  ('x80g-27', 'Biology'),
  ('x80g-27', 'Chemistry'),
  ('x80g-27', 'Computer Science'),
  ('x80g-27', 'Design Technology'),
  ('x80g-27', 'Environmental Systems & Societies'),
  ('x80g-27', 'Physics'),
  ('x80g-27', 'Sports, Exercise & Health Science'),
  ('x80g-27', 'Mathematics: Analysis & Approaches'),
  ('x80g-27', 'Mathematics: Applications & Interpretation'),
  ('x80g-27', 'Dance'),
  ('x80g-27', 'Film'),
  ('x80g-27', 'Music'),
  ('x80g-27', 'Theatre'),
  ('x80g-27', 'Visual Arts'),
  ('x80g-27', 'Theory of Knowledge'),
  ('x80g-27', 'Extended Essay'),
  ('x80g-27', 'Creativity, Activity, Service'),
  ('x80g-28', 'Language'),
  ('x80g-28', 'Social Studies'),
  ('x80g-28', 'Mathematics'),
  ('x80g-28', 'Science'),
  ('x80g-28', 'Arts'),
  ('x80g-28', 'Personal, Social & Physical Education'),
  ('x80g-28', 'Language & Literature'),
  ('x80g-28', 'Language Acquisition'),
  ('x80g-28', 'Individuals & Societies'),
  ('x80g-28', 'Sciences'),
  ('x80g-28', 'Physical & Health Education'),
  ('x80g-28', 'Design'),
  ('x80g-28', 'Language A: Literature'),
  ('x80g-28', 'Language A: Language & Literature'),
  ('x80g-28', 'Literature & Performance'),
  ('x80g-28', 'Language B'),
  ('x80g-28', 'Language ab initio'),
  ('x80g-28', 'Classical Languages'),
  ('x80g-28', 'Business Management'),
  ('x80g-28', 'Digital Society'),
  ('x80g-28', 'Economics'),
  ('x80g-28', 'Geography'),
  ('x80g-28', 'Global Politics'),
  ('x80g-28', 'History'),
  ('x80g-28', 'Philosophy'),
  ('x80g-28', 'Psychology'),
  ('x80g-28', 'Social & Cultural Anthropology'),
  ('x80g-28', 'World Religions'),
  ('x80g-28', 'Biology'),
  ('x80g-28', 'Chemistry'),
  ('x80g-28', 'Computer Science'),
  ('x80g-28', 'Design Technology'),
  ('x80g-28', 'Environmental Systems & Societies'),
  ('x80g-28', 'Physics'),
  ('x80g-28', 'Sports, Exercise & Health Science'),
  ('x80g-28', 'Mathematics: Analysis & Approaches'),
  ('x80g-28', 'Mathematics: Applications & Interpretation'),
  ('x80g-28', 'Dance'),
  ('x80g-28', 'Film'),
  ('x80g-28', 'Music'),
  ('x80g-28', 'Theatre'),
  ('x80g-28', 'Visual Arts'),
  ('x80g-28', 'Theory of Knowledge'),
  ('x80g-28', 'Extended Essay'),
  ('x80g-28', 'Creativity, Activity, Service'),
  ('x80g-29', 'Language'),
  ('x80g-29', 'Social Studies'),
  ('x80g-29', 'Mathematics'),
  ('x80g-29', 'Science'),
  ('x80g-29', 'Arts'),
  ('x80g-29', 'Personal, Social & Physical Education'),
  ('x80g-29', 'Language & Literature'),
  ('x80g-29', 'Language Acquisition'),
  ('x80g-29', 'Individuals & Societies'),
  ('x80g-29', 'Sciences'),
  ('x80g-29', 'Physical & Health Education'),
  ('x80g-29', 'Design'),
  ('x80g-29', 'Language A: Literature'),
  ('x80g-29', 'Language A: Language & Literature'),
  ('x80g-29', 'Literature & Performance'),
  ('x80g-29', 'Language B'),
  ('x80g-29', 'Language ab initio'),
  ('x80g-29', 'Classical Languages'),
  ('x80g-29', 'Business Management'),
  ('x80g-29', 'Digital Society'),
  ('x80g-29', 'Economics'),
  ('x80g-29', 'Geography'),
  ('x80g-29', 'Global Politics'),
  ('x80g-29', 'History'),
  ('x80g-29', 'Philosophy'),
  ('x80g-29', 'Psychology'),
  ('x80g-29', 'Social & Cultural Anthropology'),
  ('x80g-29', 'World Religions'),
  ('x80g-29', 'Biology'),
  ('x80g-29', 'Chemistry'),
  ('x80g-29', 'Computer Science'),
  ('x80g-29', 'Design Technology'),
  ('x80g-29', 'Environmental Systems & Societies'),
  ('x80g-29', 'Physics'),
  ('x80g-29', 'Sports, Exercise & Health Science'),
  ('x80g-29', 'Mathematics: Analysis & Approaches'),
  ('x80g-29', 'Mathematics: Applications & Interpretation'),
  ('x80g-29', 'Dance'),
  ('x80g-29', 'Film'),
  ('x80g-29', 'Music'),
  ('x80g-29', 'Theatre'),
  ('x80g-29', 'Visual Arts'),
  ('x80g-29', 'Theory of Knowledge'),
  ('x80g-29', 'Extended Essay'),
  ('x80g-29', 'Creativity, Activity, Service')
) as v(level_slug, subject_name)
join public.taxonomy_levels l on l.slug = v.level_slug
on conflict do nothing;

commit;
